### ISSUE TITLE
Enhancement for pure_pursuit to look for nearest point in front

### ISSUE THREAD

**Issue by MishkaMN** [usdot-fhwa-stol/carma-platform#1015]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [X] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

Testing on integration/routing showed that the vehicle’s inability to reach its target speed was linked to the pure_pursuit node getting the speed from the nearest waypoint. Since the nearest waypoint is set to the current vehicle speed this results in effectively 0 acceleration in some cases. A work around was to drop the first point from the pure_pursuit_wrapper however this creates an implicit contract in the interface between pure_pursuit_wrapper and pure_pursuit. It would be better to update pure_pursuit to look for the waypoint in front of it and using that to set the target speed. 

Pure pursuit currently takes the first point's speed, which is why dropping the first point in pure_pursuit_wrapper worked before.
Part of the idea for this change was to remove the need for the guarantee of first point being vehicle location from this node. Doing so will make it more reusable with other controller plugins/wrappers such as platooning. So ideally the node will use the correct next point regardless of whether the first point is the vehicle location or not.

### Carma version where this issue was discovered

carma-platform develop 3.4.0+
this was found when trying to merge integration/routing to develop.

### Expected behavior
- speed on UI should be close to speed limit at a reasonable range depending on the road's condition (curvatures, turns etc).
- inlanecruising sets the trajectory points and speeds associated on each. Those speeds should be matching to those being output by pure_pursuit_wrapper. 
- pure_pursuit should pick the speed of the point that is closest to the vehicle, yet that is in front, not back without assuming the first point in the waypoint is the vehicle's position.

### Actual behavior

- car has reasonable speed, meets above criteria
- speeds do not match because the equations used is not accurate. Inlanecruising has been refactored and is using previous_speed to calculate the next speed, but when wrapper is calculating those speeds back, it is not using previous_speed so there is small accuracy problem.
- Due to the fact that pure_pursuit can't look the point in front, wrapper is dropping first point as explained above.

### Steps to reproduce the actual behavior

- carma start all
- observe final speeds in inlanecruising and output of pure_pursuit_wrapper's waypoint's speeds (accuracy mismatch and 1 point dropped)
- put print statements of current_pose and the first point in the waypoints in pure_pursuit and see that the point is behind our current_pose if we did not drop the first point. This may or may not happen, but it has potential to happen, which we don't want.

**Comment by msmcconnell** [comment]
Resolved by above PRs
