### ISSUE TITLE
Crosstrack error detection requires a more detailed process

### ISSUE THREAD

**Issue by lewisid** [usdot-fhwa-stol/carma-platform#1024]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [x] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

The design for detecting route crosstrack error needs to be more thorough in its examination as opposed to only measuring CTE relative to the "route centerline", as that line may move laterally as the road geometry changes, even though the vehicles trajectory keeps it going in a straight line. The route node already has logic that detects when a vehicle takes a different road segment (way off the planned route), but if it is staying on the same road segment, but maybe drifts past the edge of the road, or localization provides an erroneous solution, the system needs to be able to detect that and warn the operator.

### Carma version where this issue was discovered

3.4.1
### Expected behavior
Carma should be able to provide a safety mechanism for handling situations when it deviates from the planned route enough to put the vehicle in danger, such as running off the side of the road.
### Actual behavior

The logic to determine if the vehicle has departed the route is not thorough enough to detect when cases such as crosstrack error occur. This detection is limited to a single line checking the crosstrack maximum in relation to crosstrack distance and nothing else.

**Comment by msmcconnell** [comment]
Resolved by above PR
