### ISSUE TITLE
Carma requires functionality to use vehicle's current position as the starting point when generating the route

### ISSUE THREAD

**Issue by lewisid** [usdot-fhwa-stol/carma-platform#1051]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [x] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

Route generation in Carma is meant to use HD mapping to create a route from the vehicle's position to a specified destination point in the route.csv file. There is currently no logic that uses the vehicle's position as the starting point in the generation process. Instead, the route's starting point is determined by the first set of coordinates in the route.csv file.
### Carma version where this issue was discovered

carma-platform develop 3.4.0

### Expected behavior
The route uses the vehicle's current position as the starting point when creating the route to be followed.
### Actual behavior

See the description above.
### Steps to reproduce the actual behavior

1. Start Carma
2. Open the UI and select the route
3. Open Rviz and localize. Once localization is complete, the route indicators will show the start of the route corresponding to the lanelet of the first coordinate listed in the route.csv file in /opt/carma/route.

**Comment by msmcconnell** [comment]
Added in #1055
