### ISSUE TITLE
Cannot restart same route after getting LEFT ROUTE event

### ISSUE THREAD

**Issue by msmcconnell** [usdot-fhwa-stol/carma-platform#1057]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

After getting a LEFT ROUTE event, I was unable to reselect the same route on the UI. I recieved the ALREADY_FOLLOWING_ROUTE error. 

### Carma version where this issue was discovered

release/vanden-plas
### Expected behavior
You can restart the same route after leaving it. 
### Actual behavior

See description
### Steps to reproduce the actual behavior

1. Select route and drive
2. leave route
3. Got LEFT ROUTE notification on UI and hit Restart
4. Selected route again from UI
5. Got ALREADY_FOLLOWING_ROUTE notification on UI and was not able to reselect the route.

**Comment by msmcconnell** [comment]
Resolved by above PRs

**Comment by dan-du-car** [comment]
reopen due to another pending PR

**Comment by dan-du-car** [comment]
Close per PR merged
