### ISSUE TITLE
Non-valid route files reported from route node to UI as "0"

### ISSUE THREAD

**Issue by msmcconnell** [usdot-fhwa-stol/carma-platform#1062]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

When there is an invalid route file (as in does not match file spec), in the /opt/carma/routes folder then the route node will still report it as available to the UI with an empty id that is shown as "0" on the UI. Ideally such files wouldn't be reported at all 
### Carma version where this issue was discovered

release/vanden-plas
### Expected behavior
Only files matching a valid route spec are reported to the UI
### Actual behavior

See description
### Steps to reproduce the actual behavior

Add an old waypoint file to the routes folder and run carma to observe how it is shown on the UI.

**Comment by MishkaMN** [comment]
Resolved by above PR
