### ISSUE TITLE
Implement direct MobilityPath to ExternalObject conversion in motion_prediction node

### ISSUE THREAD

**Issue by MishkaMN** [usdot-fhwa-stol/carma-platform#1067]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [X] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

To support the cooperative lane change design, we want to use MobilityPath data to get accurate predictions of vehicle motion for external object prediction. Unfortunate, doing a proper sensor fusion as described by CAR-2516: Detailed Design integration of Mobility Path data with world model object predictionsTO DO will take too long for Zephyr, so instead we will update out motion_prediction node to do a direct conversion of MobilityPah data to ExternalObject. This operational mode will be controlled by 
a flag with 3 states:

MOBILITY_PATH_ONLY: MobilityPath used as only source of external object data

SENSORS_ONLY: Sensors used as only source of external object data (mobility paths dropped)

PATH_AND_SENSORS: Both MobilityPath and sensors used without fusion but synchronized so the output message contains both.

### Carma version where this issue was discovered

carma 3.4.0+ develop
### Expected behavior
motion_computation node publishes objects from mobility path as well
### Actual behavior

N/A

**Comment by msmcconnell** [comment]
Resolved by above PR
