### ISSUE TITLE
Only "localhost" url accesses carma-web-ui on black pacifica. IP address brings up messenger ui

### ISSUE THREAD

**Issue by msmcconnell** [usdot-fhwa-stol/carma-platform#1075]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

Only "localhost" url accesses carma-web-ui on black pacifica. IP address brings up messenger ui. It seems that there might be a residual instance of the carma-messenger running on the black pacifica which could interfere with carma-platform operation. Another posibility is that the browser cache is not fully clearing. 
### Carma version where this issue was discovered

release/vanden-plas
### Expected behavior
localhost, ip, and shotcuts all bring up the carma-web-ui on a platform vehicle
### Actual behavior

Only localhost brings up the correct UI
### Steps to reproduce the actual behavior

Run carma and navigate to localhost then the ip address to compare behavior.

**Comment by JonSmet** [comment]
This behavior was due to a dangling Docker image that existed on the Black Pacifica prior to deploying Vanden Plas. The issue was resolved by removing the image from the vehicle.
