### ISSUE TITLE
Add Yield Tactical Plugin

### ISSUE THREAD

**Issue by saina-ramyar** [usdot-fhwa-stol/carma-platform#1089]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [x] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

A Yield tactical plugin is developed for modifying trajectories to avoid surrounding objects.

### Expected behavior
The vehicle follows moving objects at a safe distance and decelerates to a stop for stationary obstacles without collision.
### Steps to reproduce the actual behavior

N/A

**Comment by msmcconnell** [comment]
Resolved by above PRs
