### ISSUE TITLE
Ford Fusion front lightbar does not perform certain light patterns as expected

### ISSUE THREAD

**Issue by JonSmet** [usdot-fhwa-stol/carma-platform#1100]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

When connected to the lightbar via the web interface, certain lightbar pattern commands do not result in the expected pattern on the front lightbar. This issue was discovered during Vanden Plas verification testing.

### Carma version where this issue was discovered

Vanden Plas

### Expected behavior
The lightbar web interface commands listed below should result in the following behavior:
- D2: Yellow dim bars (including all three bars on each side)
- D3: Right arrow (all 6 yellow bars make a right arrow pattern)
- D4: Left arrow (all 6 yellow bars make a left arrow pattern)
- D6: Yellow flash (including all three bars on each side)
- D7: Unused - lightbars are off

### Actual behavior

- D2: Yellow dim bars - only two outer bars on each side participate
- D3: Right arrow - only two outer bars on each side participate
- D4: Left arrow - only two outer bars on each side participate
- D6: Yellow flash - only two outer bars on each side participate
- D7: Unused - two outer bars on each side are solid green

### Steps to reproduce the actual behavior

1. Start Carma
2. Using a web browser, navigate to the lightbar's web interface and login
3. Input the lightbar commands listed in this issue

**Comment by MishkaMN** [comment]
Fusion has one fewer lightbar indicator than other cars because it is small. So it is expected that only two outer bars participate on orange lights.
From looking at how the lightbar was behaving, the "apply" button may have been pressed.
I just checked the fusion as I was in the car, and confirmed they perform as expected.
