### ISSUE TITLE
Refactor plan_delegator and InLane-cruising to properly sequence maneuver/trajectory planning

### ISSUE THREAD

**Issue by msmcconnell** [usdot-fhwa-stol/carma-platform#1106]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [x] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

For the Vanden-Plas release the plan_delegator contains special case logic to handle inlane-cruising because that component plans over multiple maneuvers at once. To better support plugin interoperability, we need to update this logic to work as plan_delegator expects
### Carma version where this issue was discovered

release/vanden-plas
### Expected behavior
Each plugin adheres to the plan_delegators required interface. In this case it returns one maneuver worth of trajectory at a time. 
### Actual behavior

A trajectory for all LANE_FOLLOW maneuvers are returned for a plan request
### Steps to reproduce the actual behavior

Run a route with carma

**Comment by JonSmet** [comment]
Closed by PR #1220 in carma-platform and PR #102 in carma-msgs.
