### ISSUE TITLE
More robust lane splitting functionality

### ISSUE THREAD

**Issue by msmcconnell** [usdot-fhwa-stol/carma-platform#1110]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [x] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

The carma_wm_ctrl/test/MapTestTools.cpp file contains a unit test for splitting a loop of lanelets into two lanes. Unfortunately, the current implementation does not allow for other intersecting lanelets to exist in the base map. The test should be updated so that the lane of interest can still be split.  
### Carma version where this issue was discovered

develop after 3.4.0
### Expected behavior
See description
### Actual behavior

See description
### Steps to reproduce the actual behavior

1. Do this
1. Then do this...
run the map-tools_split_lanes unit test

**Comment by MishkaMN** [comment]
resolved by above PR
