### ISSUE TITLE
CARMA Web UI - Fix Issues with Notification Sound and Text Display

### ISSUE THREAD

**Issue by maefromm** [usdot-fhwa-stol/carma-platform#1112]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

During Vanden Plas verification, noticed that we have not regression tested the UI sound notification and text display that was copied over from CARMA2 implementation related to changes to the route and guidance states/events:

1) When overriding the vehicle and guidance goes into INACTIVE state, the following issues occur: 
a) Sound notification to the Vehicle Operator keeps repeating, when it should only be played once similar to CARMA2 implementation.
b) The notification text is for Cadillacs and no longer valid: "To re-engage, double tap the ACC switch downward on the steering wheel". Remove this. 

2) Review at the important messages shown in the Route Tab or Display Tab message boxes that are sent to the driver and ensure they are correct. The message should be displayed to the user regardless of the Tab they are in. For example, messages related to guidance or route changes or trajectory, etc. should be shown to the operator on the active tab they are in. The messages deemed important to be seen right away or get the drivers attention after a sound notification, should be displayed regardless of which tab they are on. 

3) Review the sounds related to the route and guidance states/events. Ensure they are implemented similar to CARMA2. 

Attachments below: 
https://user-images.githubusercontent.com/27976519/109180665-1b5ff400-7759-11eb-86c6-e30e60263a69.mp4
![20210224_125930](https://user-images.githubusercontent.com/27976519/109180670-1d29b780-7759-11eb-9416-ba593b377fd1.jpg)

### Carma version where this issue was discovered

Vanden Plas Candidate

### Expected behavior
Explained above. 

### Actual behavior

Explained above. 

### Steps to reproduce the actual behavior

Explained above. 

### Related work

Vanden Plas release

**Comment by dan-du-car** [comment]
close as PR is merged
