### ISSUE TITLE
roadway object plugin issue

### ISSUE THREAD

**Issue by itabrl** [usdot-fhwa-stol/carma-platform#1117]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

with correct input to the package there is empty list as an output

### Carma version where this issue was discovered

develop
### Expected behavior
output with the location of the vehicle front of the carma car

### Actual behavior

empty list as an output

**Comment by msmcconnell** [comment]
Related to https://github.com/usdot-fhwa-stol/carma-platform/issues/1068

**Comment by msmcconnell** [comment]
Resolved by PR #1145
