### ISSUE TITLE
Blue Lexus experiences high-magnitude deceleration behavior on TFHRC route

### ISSUE THREAD

**Issue by JonSmet** [usdot-fhwa-stol/carma-platform#1118]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

During Vanden Plas verification testing with a custom vector map used to specify large speed limit changes across sequential lanelets, there were several instances of the Blue Lexus reaching deceleration rates of at least -10 m/s^2. This behavior was repeatable across multiple test runs. Similar deceleration behavior was experienced when using the normal THFRC vector map as well.

### Carma version where this issue was discovered

Vanden Plas

### Expected behavior
Deceleration rates should be reasonable in magnitude.

### Actual behavior

Deceleration rates of over -10 m/s^2 occurred on the route at TFHRC.

### Steps to reproduce the actual behavior

1. Drive the Vanden Plas route in the Blue Lexus at TFHRC with the system engaged.

**Comment by msmcconnell** [comment]
This was resolved by updating the SSC max_brake and max_throller fields in the ssc json files for each vehicle.
