### ISSUE TITLE
Fix CARMA Platform Required Plugins to fix Web UI display

### ISSUE THREAD

**Issue by maefromm** [usdot-fhwa-stol/carma-platform#1130]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

Fix the required_plugins configuration file to fix the UI display of required plugins to have Route Following, InLaneCruisingPlugin, StopandWaitPlugin, Pure Pursuit.

### Carma version where this issue was discovered

Vanden Plas Candidate

### Expected behavior
The picture below should show InLaneCruisingPlugin, StopandWaitPlugin as required as well. Only 4 plugins are showing currently on Vanden Plas release and all four are required. 
![20210224_130631](https://user-images.githubusercontent.com/27976519/109691622-a07e4b00-7b55-11eb-82d6-163fddfe39ce.jpg)

### Actual behavior

See above.

### Steps to reproduce the actual behavior

See above.

**Comment by dan-du-car** [comment]
@maefromm There is no space between below plugin names: RouteFollowing, InLaneCruisingPlugin, StopandWaitPlugin. Do we need to update this name with spaces?

**Comment by maefromm** [comment]
@dan-du-car can this now be closed based on your integreation testing in vehicle?

**Comment by msmcconnell** [comment]
Resolved by above PR
