### ISSUE TITLE
Implementation of Route Invalidated event

### ISSUE THREAD

**Issue by aswath1** [usdot-fhwa-stol/carma-platform#1148]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [x] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

When a geofence is received, it is possible for it to make the current route invalid for example if a lane is closed that was part of the route. To support this, the route package state machine includes a Route Invalidated event which is meant to force a reroute operation.

### Steps to reproduce the actual behavior

1. Do this
1. Then do this...

**Comment by msmcconnell** [comment]
Resolved in above PR
