### ISSUE TITLE
Route following params misloaded

### ISSUE THREAD

**Issue by adev4a** [usdot-fhwa-stol/carma-platform#1157]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary
The config params from route following are being put into the guidance namespace instead of a route_following namespace.
This means that the variables loading these params are only using default values.
See comment here,
https://github.com/usdot-fhwa-stol/carma-platform/pull/1156#discussion_r595980898

### Expected behavior
The params should be mapped to route following's namespace and changing params in the config file should result in a change 
the loaded value.
### Steps to reproduce the actual behavior

1.Change the value of minimal_maneuver_duration to 20
2. Print the value of variable mvr_duration (which is supposed to read this param)

**Comment by msmcconnell** [comment]
Resolved by above PR
