### ISSUE TITLE
Interface Manager get_drivers_with_capabilities does NOT return cross-capabilities

### ISSUE THREAD

**Issue by maefromm** [usdot-fhwa-stol/carma-platform#116]
After discussion with Mike, he agreed that interface manager should have allowed this call which includes a list across multiple capabilities. Currently it only returns results for single capability. 

1. Single
rosservice call /saxton_cav/interface_manager/get_drivers_with_capabilities['/control/robot_status','/control/cmd_speed']
driver_data:[/saxton_cav/drivers/srx_controller/control/robot_status, /saxton_cav/drivers/srx_controller/control/cmd_speed]

2. Multiple 
rosservice call /saxton_cav/interface_manager/get_drivers_with_capabilities ['/control/robot_status','/control/cmd_speed','/control/cmd_lateral','/can/engine_speed','/can/speed','/can/acc_engaged','/comms/inbound_binary_msg','/comms/outbound_binary_msg']
driver_data: []

3. Multiple
rosservice call /saxton_cav/interface_manager/get_drivers_with_capabilities ['/control/cmd_lateral','/control/robot_status']
driver_data: []

**Comment by TonysCousin** [comment]
This issue is now OBE due to new structure and API provided by Health Monitor, which replaces Interface Manager.
