### ISSUE TITLE
Inlane cruising issues std::bad alloc at tfhrc

### ISSUE THREAD

**Issue by adev4a** [usdot-fhwa-stol/carma-platform#1169]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

While testing at tfhrc, it was noticed that an exception from inlane cruising "std::bad alloc" occurs at the intersection into the main parking lot.
The exception was consistently seen while trying to engage from this location. Testing was conducted and reproducible on white pacifica.

**Comment by JonSmet** [comment]
Closed by PR #1189.
