### ISSUE TITLE
inlane cruising issues error "No points to fit in timespan".

### ISSUE THREAD

**Issue by adev4a** [usdot-fhwa-stol/carma-platform#1171]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Actual behavior

While testing at tfhrc, inlane cruising issued a "No points to fit in timespan" error. 
### Steps to reproduce the actual behavior

1. Engage carma from near the security, on a route that goes further than the first intersection (near cia parking lot)
2. When the vehicle reaches the intersection, the exception is thrown.

**Comment by JonSmet** [comment]
Attempted to reproduce this issue on the White Pacifica and Black Pacifica at TFHRC and have been unsuccessful. No other occurrences of this exact issue have occurred since the beginning of April, and the team will re-open the issue for investigation if it returns.
