### ISSUE TITLE
Camera failing on white pacifica

### ISSUE THREAD

**Issue by adev4a** [usdot-fhwa-stol/carma-platform#1182]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

On engaging carma on the white pacifica, the camera fails and consequently carma fails.
![image(4)](https://user-images.githubusercontent.com/51463994/113018398-7fa61700-914e-11eb-86d5-8e772b5d2064.png)

### Expected behavior
Carma should start up without errors and allow route selection.
### Actual behavior
On starting up carma, the drivers are initialized, the camera fails and causes carma to crash.

### Steps to reproduce the actual behavior

1. Build image off of develop.
2. Let carma initialize and start up
3. After a few minutes carma crashes with guidance failing
4. Print out /system_alert topic , it should say "Camera failed"

**Comment by msmcconnell** [comment]
This was resolved by updating the IP address of the cameras on the white pacifica
