### ISSUE TITLE
Passenger side monitor’s cable broken on Black Pacifica

### ISSUE THREAD

**Issue by MishkaMN** [usdot-fhwa-stol/carma-platform#1191]
### Types of Issue
As title suggests, the hdmi cable is broken. Please see the picture. 

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

See above
![C2E9F00E-780E-4D64-A8B3-800E29D39246](https://user-images.githubusercontent.com/20613282/113621888-3e1fdb00-962a-11eb-8c59-903722a54841.jpeg)

### Expected behavior
Monitor should work
### Actual behavior

Monitor is black
### Steps to reproduce the actual behavior

Start the car/spectra on Black Pacifica.

**Comment by msmcconnell** [comment]
Lap staff is tracking this. Closing
