### ISSUE TITLE
Arbitrator high CPU usage prior to platform engage

### ISSUE THREAD

**Issue by kjrush** [usdot-fhwa-stol/carma-platform#1228]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

Arbitrator consumes significant CPU resources prior to the user engaging the platform

### Carma version where this issue was discovered

3.5.3

### Expected behavior

Arbitrator should not consume ~95% of a CPU core during system startup

### Actual behavior

Arbitrator appears to be fully utilizing a core with a tight spin loop.

### Steps to reproduce the actual behavior

Run `carma start all` and measure the CPU usage with `top` inside of the docker container.

**Comment by msmcconnell** [comment]
I was able to confirm the above PR resolve this behavior
