### ISSUE TITLE
Map update causing nodes using carma_wm lib crashing

### ISSUE THREAD

**Issue by dan-du-car** [usdot-fhwa-stol/carma-platform#1233]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

map_update topic in carma-wm-ctrl  publish data upon receiving trafficControlMessage from geofence topic. However, after carma_wm Listener subscribe to map_update and  update the world_model object, other carma nodes crash 

### Carma version where this issue was discovered

CARMA version 3.4.1
### Expected behavior

- map_update topic in carma-wm-ctrl  shall publish data upon receiving trafficControlMessage from geofence topic.  
-  carma nodes should behave as normail and no crashing
- WMListener shall finish applying the map update with the incoming geofence Id.
- With the updated world_model in this case lane closed, the route callback should provide a different route path in RVIZ from the original route path.

### Actual behavior

 - nodes using the carma_wm lib is crashing.

### Steps to reproduce the actual behavior

- refer to carma installation and development setup to pull/build all carma related images
- carma config set <local-image>
- carma start all
- send below data to /environment/geofence topic
```
rostopic pub /environment/geofence cav_msgs/TrafficControlMessage "{choice: 1, tcmV01: {reqid: {id: [0, 0, 0, 0, 0, 0, 0, 0]}, reqseq: 0, msgtot: 0, msgnum: 0, id: {id: [69, 224, 199, 55, 92, 94, 75, 203, 152, 182, 12, 14, 31, 177, 209, 136]}, updated: {secs: 0, nsecs: 0}, package: {label: MOVE OVER LAW, label_exists: false, tcids: []}, package_exists: true, params: {vclasses: [{vehicle_class: 0}], schedule: {start: {secs: 1619798999, nsecs: 124065661}, end: {secs: 0, nsecs: 0}, end_exists: false, dow: {dow: [0, 0, 0, 0, 0, 0, 0]}, dow_exists: false, between: [], between_exists: false, repeat: {offset: {secs: 0, nsecs: 0}, period: {secs: 0, nsecs: 0}, span: {secs: 0, nsecs: 0}}, repeat_exists: false}, regulatory: false, detail: {choice: 12, signal: [], closed: 1, chains: 0, direction: 0, lataffinity: 0, latperm: [0, 0], parking: 0, minspeed: 0, maxspeed: 20, minhdwy: 10, maxvehmass: 0, maxvehheight: 0, maxvehwidth: 0, maxvehlength: 0, maxvehaxles: 0, minvehocc: 0}}, params_exists: true, geometry: {proj: '+proj=tmerc +lat_0=38.95197911150576 +lon_0=-77.14835128349988 +k=1 +x_0=0 +y_0=0 +datum=WGS84 +units=m +vunits=m +no_defs  ', datum: '', reftime: {secs: 0, nsecs: 0}, reflon: 0, reflat: 0, refelv: 0, heading: 0, nodes: [{x: -160.147519583, 'y': 518.016083159, z: 0, z_exists: false, width: 0, width_exists: false}, {x: -160.460862378, 'y': 515.865033205, z: 0, z_exists: false, width: 0, width_exists: false}, {x: -160.81474765, 'y': 513.721877556, z: 0, z_exists: false, width: 0, width_exists: false}, {x: -161.207808552, 'y': 511.624944595, z: 0, z_exists: false, width: 0, width_exists: false}, {x: -161.591820791, 'y': 509.64486476, z: 0, z_exists: false, width: 0, width_exists: false}, {x: -161.9739893, 'y': 507.66442592, z: 0, z_exists: false, width: 0, width_exists: false}, {x: -162.354286052, 'y': 505.708595472, z: 0, z_exists: false, width: 0, width_exists: false}, {x: -162.786099743, 'y': 503.813453788, z: 0, z_exists: false, width: 0, width_exists: false}, {x: -163.296077172, 'y': 501.937509871, z: 0, z_exists: false, width: 0, width_exists: false}, {x: -163.883549676, 'y': 500.083987289, z: 0, z_exists: false, width: 0, width_exists: false}]}, geometry_exists: true}}"
```

-nodes using the carma_wm lib is crashing.

**Comment by msmcconnell** [comment]
Resolved by above PRs
