### ISSUE TITLE
Guidance silently refused to plan some trajectories

### ISSUE THREAD

**Issue by qswawrq** [usdot-fhwa-stol/carma-platform#124]
During I-95 test on NB 65 mph route, arbitrator stops to plan any trajectories after planning trajectory spanning [10420.896801400624, 10481.931957650624), which causes the vehicle never able to join the platoon. But the CARMA guidance is always ENGAGED.
[guidance.txt](https://github.com/fhwa-saxton/CarmaPlatform/files/2113049/guidance.txt)

**Comment by darrelld05** [comment]
This issue was transferred from the original CARMAPlatform: Old issue # 927

**Comment by TonysCousin** [comment]
Applies to Carma2 architecture, so is now OBE.
