### ISSUE TITLE
motion prediction reports wrong speed on prediction state

### ISSUE THREAD

**Issue by itabrl** [usdot-fhwa-stol/carma-platform#1244]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

motion prediction reports wrong speed on prediction state part of roadway object message
### Carma version where this issue was discovered

zephyr 
### Expected behavior
correct speed
### Actual behavior

speed is reported small

**Comment by msmcconnell** [comment]
Believed to be resolved by above PR
