### ISSUE TITLE
Vehicle going over the curb while lane changing left at tfhrc

### ISSUE THREAD

**Issue by adev4a** [usdot-fhwa-stol/carma-platform#1254]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

While testing lane change at tfhrc at 25mph, it was found that vehicle tends to go over the curb while moving from left to right.

### Expected behavior
The vehicle should be able to run the entire route with the required lane changes.

### Actual behavior
During the test conducted the vehicle was made to lane follow, lane change from right to left, lane follow and then lane change from left to right again to mimic the test case required for verification testing.
The vehicle was able to make the first lane change without any error, but ran over the curb during the second error.

### Steps to reproduce the actual behavior

1. Start from the right lane on innovation drive behind the first intersection
2. Choose the TFHRC_TIM_CCW.osm map
3. Engage Carma over TFHRC_TIM_EAST_DEST_RIGHT

**Comment by msmcconnell** [comment]
This was resolved by above PR
