### ISSUE TITLE
Platooning Plugin Has Conflicts with Cooperative Merge Plugin

### ISSUE THREAD

**Issue by qswawrq** [usdot-fhwa-stol/carma-platform#126]
On I-95 testing, the complex maneuver planned by cooperative merge plugin is deleted by Platooning Plugin. The intention is to join a platoon after we finished merging. However, platooning plugin started to plan a new trajectory once it finished negotiation with the pass-by platoon, when it is still on the ramp (it should be under control of RSU).

**Comment by darrelld05** [comment]
This issue was transferred from the original CARMAPlatform: Old issue # 923

**Comment by TonysCousin** [comment]
Applies to Carma2 architecture, so is now OBE.
