### ISSUE TITLE
Vehicle drives through route end point without decelerating and remains engaged until driver takeover.

### ISSUE THREAD

**Issue by JonSmet** [usdot-fhwa-stol/carma-platform#1262]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

During Zephyr low-speed verification testing at TFHRC, is was discovered that a vehicle will drive through its route end point without decelerating (on a straight road with a speed limit of 25 mph, the vehicle will travel through the route end point at 25 mph) and remain engaged until a driver takeover occurs. 

### Carma version where this issue was discovered

Zephyr

### Expected behavior
Expected behavior is that a vehicle will smoothly decelerate and come to a complete stop at or slightly before the route end point.

### Actual behavior

Described above.

### Steps to reproduce the actual behavior

1. Start carma with the Zephyr candidate release
2. Select a valid route and engage the system. Allow the system to reach the end of its route.
3. Verify that the vehicle travels through the route end point (this exact point can be verified by checking the final point in the route file or the final path point displayed in rviz) without decelerating. Additionally, verify that driver takeover is required to disengage the system (alternatively, the E-Stop can be pressed).

**Comment by msmcconnell** [comment]
This is resolved in the A1 release
