### ISSUE TITLE
CARMAWeb UI - Logout does should issue a shutdown of the platform

### ISSUE THREAD

**Issue by maefromm** [usdot-fhwa-stol/carma-platform#1277]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

The Logout button on the UI should issue a carma-platform shutdown. All images should be stopped except for carma web ui, when you issue a "docker ps". Then user can do another remote login to start up all the carma-platform image and any related images. 

### Carma version where this issue was discovered

Zephr Candidate Release 

### Expected behavior
See description above. 

### Actual behavior

See description above. 

### Steps to reproduce the actual behavior

1. Login using the CARMA Web UI. 
2. Run 'docker ps" to ensure all images are running. 
3. Logout using the CARMA Web UI. 
3. Run "docker ps" to ensure all images has been stopped or not showing, except for carma web ui.

**Comment by msmcconnell** [comment]
Resolved by above PR
