### ISSUE TITLE
Rosbag Matching

### ISSUE THREAD

**Issue by jsun6065** [usdot-fhwa-stol/carma-platform#1289]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [x] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

Rosbags are difficult to match to their corresponding log directory because the log directories have unintuitive names that do not indicate which bag file they belong to. 

### Carma version where this issue was discovered

Latest version
### Actual behavior

Log directories are named as an ID which makes it difficult to match them to a rosbag
### Steps to reproduce the actual behavior

1. Gather a Rosbag
2. Try to match it to a large log file that has many log directories

**Comment by TonysCousin** [comment]
Closed as implemented in PR #1290.
