### ISSUE TITLE
Complex Replan Trigger Does Not Delete Itself

### ISSUE THREAD

**Issue by Supraluminal** [usdot-fhwa-stol/carma-platform#129]
Complex replan triggers setup in Arbitrator are supposed to delete themselves from the trajectory progress callback list after being called, but this is not the case, leading to 1 invocation, then 2, then 3, then 4, escalating with each trajectory planned.

Performance impact is likely low, as callback is very small and not observed to get above 10-12 executions, and only done once per trajectory, but is notable issue.

**Comment by darrelld05** [comment]
This issue was transferred from the original CARMAPlatform: Old issue # 914

**Comment by TonysCousin** [comment]
Applies to Carma2 architecture, so is now OBE.
