### ISSUE TITLE
carma_wm_ctrl unit tests are failing

### ISSUE THREAD

**Issue by MishkaMN** [usdot-fhwa-stol/carma-platform#1297]
### Types of Issue

- [X] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

While working on https://github.com/usdot-fhwa-stol/carma-platform/issues/1296, I noticed that many of the unit tests of carma_wm_ctrl were failing before any implementation for that PR had started. 
Initial quick research suggests that the recent change with how boundaries are processed in carma_wm_ctrl is affecting which lanelets are being picked. Also some of the failures maybe due to the geofence schedule logic revamp which happened here https://github.com/usdot-fhwa-stol/carma-platform/commit/0ad8c40052d119e2464b866c15175ead3d287533#diff-45f4f5dd275a8bb166958b1c435962f6cd4a378a74d0ac31c71862bf5d344030 
The problem may lie in a different place.

### Carma version where this issue was discovered

release/zephyr branch, platform 3.6.0+
### Expected behavior
unit tests should pass
### Actual behavior

![image](https://user-images.githubusercontent.com/20613282/121111777-7a63e900-c7dd-11eb-8495-6780c0fbd6f5.png)

### Steps to reproduce the actual behavior

1. checkout release/zephyr branch
2. run unit test on carma_wm_ctrl

**Comment by msmcconnell** [comment]
Resolved by above PR
