### ISSUE TITLE
/guidance/route_state stops publishing after a carma3/Incident_Use_Case MobilityOperation message is received and processed.

### ISSUE THREAD

**Issue by JonSmet** [usdot-fhwa-stol/carma-platform#1306]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

It is expected that the /guidance/route_state topic always has messages published to it by the Route package after a route has been selected. This data is used by the Web UI and is very useful for rosbag data analysis. 

During TIM Use Case data analysis, it was discovered that messages are no longer published to the /guidance/route_state topic after the first the vehicle first receives a valid carma3/Incident_Use_Case MobilityOperation message. It is assumed that this bug is somehow related to the map update that occurs when TrafficIncidentParserWorker publishes a TrafficControlMessageV01 that is processed by WMBroadcaster.

### Carma version where this issue was discovered

Zephyr Release Branch

### Expected behavior
Messages are always published to the /guidance/route_state topic after a route has been selected.

### Actual behavior

Please see actual behavior above.

### Steps to reproduce the actual behavior

1. Select a route and monitor the /guidance/route_state topic
2. Receive a valid carma3/Incident_Use_Case MobilityOperation message (or publish one manually) that affects the selected route.
3. Check whether messages are still being published to the /guidance/route_state topic

**Comment by msmcconnell** [comment]
Resolved by above PR
