### ISSUE TITLE
Cooperative Lanechange Unit tests are failing

### ISSUE THREAD

**Issue by MishkaMN** [usdot-fhwa-stol/carma-platform#1308]
### Types of Issue

- [X] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

Cooperative lanechange unit test is failing with both failing tests come from WMTestLibForGuidance.h with text:
`C++ exception with description "There was an error in routing using the given lanelets in setRouteByLanelets" thrown in the test body.` 
![image](https://user-images.githubusercontent.com/20613282/121876723-d942ca00-ccd7-11eb-83d4-d8bf98de5a56.png)

### Carma version where this issue was discovered

3.6.0+ release/zephyr
### Expected behavior
Unit tests pass
### Actual behavior

See above.
### Steps to reproduce the actual behavior

run unit tests on release/zephyr

**Comment by adev4a** [comment]
Resolved by recent changes to branch
![image](https://user-images.githubusercontent.com/51463994/123294240-ade38a80-d4e2-11eb-9503-88c6eb1037a9.png)
