### ISSUE TITLE
Undefined behavior in `EntryManager` function

### ISSUE THREAD

**Issue by adamlm** [usdot-fhwa-stol/carma-platform#1336]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

The `EntryManager::is_camera_entry_required` function in `health_monitor/src/entry_manager.cpp` could potentially fall off without returning a value, which is considered undefined behavior. The function iterates through a `std::vector` of `std::strings` searching for a match to `name`. If a match is found, the function returns the match's index. Otherwise, the function falls off without returning a value.

### Carma version where this issue was discovered

Issue discovered in `develop`. It was introduced in commit 6d12189f90e0eba605e7524f464f9be82d513109.

### Expected behavior
`health_monitor` package should compile without warning.

### Actual behavior

Package compiles, but with a compiler warning:
```
/tmp/tmp_ws/src/health_monitor/src/entry_manager.cpp:116:5: warning: control reaches end of non-void function [-Wreturn-type]
     }
     ^
```

### Steps to reproduce the actual behavior

1. Clone the repository into a ROS workspace
    ```shell
    $ cd catkin_ws/src
    $ git clone https://github.com/usdot-fhwa-stol/carma-platform.git
    ```
2. Compile the `health_monitor` node
    ```shell
    $ cd carma-platform
    $ catkin_make --only-pkg-with-deps health_monitor
    ```

**Comment by msmcconnell** [comment]
This was resolved in https://github.com/usdot-fhwa-stol/carma-platform/pull/1286
