### ISSUE TITLE
Add Platooning Strategic, Tactical and Control Plugins

### ISSUE THREAD

**Issue by saina-ramyar** [usdot-fhwa-stol/carma-platform#1344]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [x] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary
Platooning Strategic, Tactical and Control Plugins are developed to enable CARMA Platform to perform platooning.

### Expected behavior
A platoon is formed and maintained once multiple vehicles are in a lane.
### Steps to reproduce the actual behavior

1. Do this
1. Then do this...

**Comment by msmcconnell** [comment]
Resolved by above PRs
