### ISSUE TITLE
Fix ILC "no points to fit in time span" exception 

### ISSUE THREAD

**Issue by MishkaMN** [usdot-fhwa-stol/carma-platform#1347]
### Types of Issue

There are bugs in route_following_plugin and inlanecruising_plugin which gives above error in title. It was found during platooning test. route_following_plugin's bug was introduced in recent lane_change PR, and inlanecruising_plugin needs a fix as current buffer_ending_downtrack is not doing anything since available lanelets to operate on are calculated by ignoring this downtrack.

- [X] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

See above. 
### Carma version where this issue was discovered

carma-system:3.6.0+
### Expected behavior
no exception.
### Actual behavior

gives above error

**Comment by msmcconnell** [comment]
Resolved by above PR
