### ISSUE TITLE
Route Following doesn't update speed limit if route not updated

### ISSUE THREAD

**Issue by adev4a** [usdot-fhwa-stol/carma-platform#1351]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

The current implementation of route following creates a maneuver plan when the route is set. Before passing the maneuver to the response the starting speed is updated but the ending speed is not changed.

If a geofence message is published to update the speed limit without changing the route, the route_cb will not be triggered and the speed limit will remain unchanged from before. 

### Expected behavior
The speed limit in the maneuver should reflect the current speed limit at all times.
### Steps to reproduce the actual behavior

1. Publish a geofence message to update only speed limit of lanelet without changing route
2. Check speed limit on UI and compare with actual speed of vehicle when passing through.

**Comment by msmcconnell** [comment]
Resolved by above PR
