### ISSUE TITLE
Work Zone: Intersection Transit Maneuvering Implementation

### ISSUE THREAD

**Issue by lewisid** [usdot-fhwa-stol/carma-platform#1366]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [x] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

The Work Zone use case is in need of a node that can process intersection transit maneuvering messages sent from Carma Cloud. This plugin will be able to discern when such messages are being used and will convert those messages into lane following maneuvers to be passed into in-lane cruising. From there, the plugin will be able to provide trajectory calculations for the vehicle to follow.
### Expected behavior
See the description.
### Actual behavior

This node does not exist yet.

**Comment by msmcconnell** [comment]
Resolved by above PR
