### ISSUE TITLE
Typo for ManeuverParameters value "negotiation_type"

### ISSUE THREAD

**Issue by lewisid** [usdot-fhwa-stol/carma-platform#1371]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [x] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

There is a typo in  both carma-platform and carma-msgs where the ManeuverParameters.msg value "negotiation_type" is incorrectly spelled as "neogition_type" in multiple files
### Carma version where this issue was discovered

3.6.0
### Steps to reproduce the actual behavior

1. Do this
1. Then do this...

**Comment by msmcconnell** [comment]
Resolved by above PRs
