### ISSUE TITLE
C1T - Missing `robot_state_publisher` package in Docker container

### ISSUE THREAD

**Issue by adamlm** [usdot-fhwa-stol/carma-platform#1378]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

The C1T version of `carma-platform` Docker container is missing the `robot_state_publisher` package, which is preventing `carma.urdf` static transforms from being published. This package is supposed to be pre-installed in the `carma-base` Docker container image.

### Carma version where this issue was discovered

Affects the `noetic-f1tenth/develop` branch.

### Expected behavior
The Transforms component of `carma-platform` reads the `carma.urdf` file and publishes static transforms.

### Actual behavior

The Transforms component of `carma-platform` fails to launch because the `robot_state_package` is not installed.

### Steps to reproduce the actual behavior

1. Set up a C1T configuration using the existing `carma-platform:noetic-f1tenth-develop` Docker image
2. Start CARMA
    ```shell
    $ carma start all
    ```
3. Examine the logs for `carma-platform`

**Comment by msmcconnell** [comment]
Resolved by above PR
