### ISSUE TITLE
Cannot build `map_file` package and dependencies from source

### ISSUE THREAD

**Issue by adamlm** [usdot-fhwa-stol/carma-platform#1380]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

When trying to build the `map_file` package and its dependencies from source, the build fails because the `vector_map_msgs` package cannot be found. The package dependency is: `map_file`->`vector_map`->`vector_map_msgs`. Upon inspection of the `vector_map_msgs` package, I found a `COLCON_IGNORE` file. Removing the file fixed the issue.

The referenced PR (usdot-fhwa-stol/autoware.ai#156) mentions this was done to avoid building unnecessary packages. However, this breaks any complete builds from source, which is necessary for deploying C1T in Docker.

### Carma version where this issue was discovered

This affects the `noetic/develop` branch for the [usdot-fhwa-stol/autoware.ai](https://github.com/usdot-fhwa-stol/autoware.ai) repository.

### Expected behavior
`colcon` (rather `catkin_make_isolated`) can successfully build `map_file` package and dependencies from source.

### Actual behavior

`map_file` package fails to build because the `vector_map_msgs` dependency is ignored by the build tool.

### Steps to reproduce the actual behavior

1. In an empty ROS workspace, clone all source dependencies for `map_file` package
2. Install system dependencies (non-ROS package dependencies) through `apt`
3. Attempt to build only `map_file` package and its dependents
    ```shell
    $ catkin_make_isolated --install --only-pkg-with-deps map_file
    ```

### Related work

usdot-fhwa-stol/autoware.ai#156

**Comment by msmcconnell** [comment]
Resolved by above PR
