### ISSUE TITLE
Integration test Workzone communication

### ISSUE THREAD

**Issue by MishkaMN** [usdot-fhwa-stol/carma-platform#1388]
### Types of Issue

- [X] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

Integration test all communication logic for workzone implementations

### Carma version where this issue was discovered

3.6.0+ develop
### Expected behavior
Workzone geometry changes upon TCM
SPAT message can be correctly processed

### Actual behavior

NA
### Steps to reproduce the actual behavior

NA

**Comment by msmcconnell** [comment]
Integration testing was completed and the fixes merged in the above PRs.
