### ISSUE TITLE
Convert map message functionality to C++

### ISSUE THREAD

**Issue by lewisid** [usdot-fhwa-stol/carma-platform#1391]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [x] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

To support the upgrade to ROS1 Noetic and ROS2 all java code must be removed from the system. This story is part of a set of stories to convert the java message package to C++ and integrate its logic with the newer cpp_message package. The scope of this story is to specifically port the Map message functionality from the Java Message node to the cpp_message node. Only the decoding of the Map needs to be completed as encoding is not required for carma-platform.
### Carma version where this issue was discovered

3.6.0

**Comment by msmcconnell** [comment]
Resolved by above PR
