### ISSUE TITLE
`RouteGeneratorWorker` erroneously warns about no central line points

### ISSUE THREAD

**Issue by adamlm** [usdot-fhwa-stol/carma-platform#1395]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

The `No central line points! Returning` warning in the `RouteGeneratorWorker` is backwards. It only warns about missing points when there are points. When there are no points, no warning is published.

### Carma version where this issue was discovered

Affects `noetic/develop` and `noetic-f1tenth/develop`.

### Expected behavior

`RouteGeneratorWorker` warns about no central line points when the route has no central line points.

### Actual behavior

`RouteGeneratorWorker` warns about no central line points when the route does have them.

### Steps to reproduce the actual behavior

1. Start up CARMA with the `noetic/develop` or `noetic-f1tenth/develop` branch
2. Select a route known to have centerlines
3. Observe log from `route` node

Alternatively, by inspection of `route_generator_worker.cpp`

**Comment by msmcconnell** [comment]
Resolved by sync with the 3.7 release
