### ISSUE TITLE
Route Following Plugin advertises incorrect plugin name

### ISSUE THREAD

**Issue by kjrush** [usdot-fhwa-stol/carma-platform#1400]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

The advertised plugin name for a plugin (as reported in the PluginDiscovery message) should match the plugin's node name (and the name used in the maneuver's planning_strategic_plugin field). Currently this is not the case for RouteFollowingPlugin. 

### Carma version where this issue was discovered
Zephyr

### Expected behavior
The reported name should match the node name

### Actual behavior

RFP advertises "RouteFollowing" in the plugin discovery message and "RouteFollowingPlugin" in other locations.

### Steps to reproduce the actual behavior
1. Run CARMA.
2. Echo the plugin discovery topic
3. Echo the maneuver plan topic from arbitrator

**Comment by JonSmet** [comment]
This issue currently exists for all strategic, tactical, and control plugins. The below list includes the current broadcasted name (to the plugin discovery topic), along with the expected broadcasted name, for each plugin in the current CARMA system:

- Route Following Plugin: Broadcasts 'RouteFollowing'; expected 'route_following_plugin'
- In Lane Cruising Plugin: Broadcasts 'InLaneCruisingPlugin'; expected 'inlanecruising_plugin'
- Stop and Wait Plugin: Broadcasts 'StopandWaitPlugin'; expected 'stop_and_wait_plugin'
- Unobstructed Lane Change Plugin: Broadcasts 'UnobstructedLaneChangePlugin'; expected 'unobstructed_lanechange'
- Cooperative Lane Change Plugin: Broadcasts 'CooperativeLaneChangePlugin'; expected 'cooperative_lanechange'
- Yield Plugin: Broadcasts 'YieldPlugin'; expected 'yield_plugin'
- Pure Pursuit Plugin: Broadcasts 'Pure Pursuit'; expected 'pure_pursuit_wrapper_node'

There is a chance I may have missed plugins that have recently been added to the system.
