### ISSUE TITLE
Silver Lexus PC Freezes at Startup

### ISSUE THREAD

**Issue by lewisid** [usdot-fhwa-stol/carma-platform#1410]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

While attempting to start up Ubuntu on the Silver Lexus, the PC would only get as far as the initial login screen before completely freezing. The keyboard inputs do not work at all. Attempting to restart Ubuntu in Recovery Mode leads to the PC freezing before the process can be completed. Additionally, when trying to modify boot settings in BIOS, the system will reboot itself randomly with no user input.
### Expected behavior
The Silver Lexus PC starts up and allows the user to access Ubuntu.
### Actual behavior

Please see description above.
### Steps to reproduce the actual behavior

1. Start the vehicle
2. Switch on the PC

**Comment by msmcconnell** [comment]
This was resolved. Closing
