### ISSUE TITLE
Workzone full integration testing

### ISSUE THREAD

**Issue by MishkaMN** [usdot-fhwa-stol/carma-platform#1417]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [X] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

Integration test the full work zone use case start to finish on real vehicles. 

### Carma version where this issue was discovered

NA
### Expected behavior
NA
### Actual behavior

NA
### Steps to reproduce the actual behavior

NA

**Comment by msmcconnell** [comment]
Integration testing was completed and changes applied when the above PR was merged. Verification testing is now underway
