### ISSUE TITLE
Speed Profile Case Determination for Trajectory

### ISSUE THREAD

**Issue by saina-ramyar** [usdot-fhwa-stol/carma-platform#1418]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [x] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

As CARMA Platform operating on a subject vehicle, I want to plot a trajectory profile to an stop-controlled intersection based on a calculated Estimated Stopping Time and acceptable acceleration and deceleration rates so that I minimize stopping time, energy consumption, and shockwave effect. Depending on the Estimated Stopping Time, three main trajectory cases are possible. I should determine which trajectory case I should follow.

### Steps to reproduce the actual behavior

1. Do this
1. Then do this...

**Comment by msmcconnell** [comment]
Resolved by above PR
