### ISSUE TITLE
CARMA-WEB-UI: traffic signal intersection id and group id  are not available

### ISSUE THREAD

**Issue by dan-du-car** [usdot-fhwa-stol/carma-platform#1420]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

There is one traffic signal controller respectively at each side of the road to signalize the vehicle whether the vehicle should stop at the intersection or not. In another word, there are two traffic signal controllers in total for the workzone use case. 

The traffic signal controllers are constantly sending signal to v2xhub. V2xhub forward the corresponding SPAT messages to the SV vehicle. However, vehicle OBU receives all the SPAT messages from both traffic signal controllers. The Platform and UI need to process/display the SPAT correctly and distinguish which SPAT is from the approaching traffic signal controller for the SV. 
### Carma version where this issue was discovered

carma-3.7.0

### Expected behavior
UI should only display the SPAT that  is from the approaching traffic signal controller for the SV. 
### Actual behavior

Currently, the UI subscribe to all incoming SPAT messages and cannot distinguish the SPAT sources in terms of which traffic signal controller is sending the signal.

### Steps to reproduce the actual behavior

N/A

**Comment by MishkaMN** [comment]
closed with above PRs
