### ISSUE TITLE
ACM testing hotfixes

### ISSUE THREAD

**Issue by MishkaMN** [usdot-fhwa-stol/carma-platform#1424]
### Types of Issue

- [X] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

Hotfixes for 3.7.0 need to be applied as 3.7.1

### Expected behavior
NA
### Actual behavior

NA
### Steps to reproduce the actual behavior
NA
### Related work

NA

**Comment by msmcconnell** [comment]
Closed in favor of detailed issue descriptions
