### ISSUE TITLE
Blue Lexus kvaser misconfiguration

### ISSUE THREAD

**Issue by MishkaMN** [usdot-fhwa-stol/carma-platform#1435]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [X] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

Carma was shutting down after starting on Blue Lexus. It did not have any explicit error messages.

However, for a brief moment it was running, running below command returned folllowing.
`rostopic echo /hardware_interface/pacmod/as_tx/all_system_statuses` returns this:
header: 
  seq: 5
  stamp: 
    secs: 0
    nsecs:         0
  frame_id: ''
enabled_status: []
overridden_status: []
fault_status: []
---`
whereas it usually returns something like this

`header: 
  seq: 1187
  stamp: 
    secs: 0
    nsecs:         0
  frame_id: ''
enabled_status: 
  - 
    key: "Accelerator"
    value: "False"
  - 
    key: "Brakes"
    value: "False"
  - 
    key: "Headlights"
    value: "False"
  - 
    key: "Horn"
    value: "False"
  - 
    key: "Shifter"
    value: "False"
  - 
    key: "Steering"
    value: "False"
  - 
    key: "Turn Signals"
    value: "False"
overridden_status: 
  - 
    key: "Accelerator"
    value: "False"
  - 
    key: "Brakes"
    value: "False"
  - 
    key: "Headlights"
    value: "False"
  - 
    key: "Horn"
    value: "False"
  - 
    key: "Shifter"
    value: "False"
  - 
    key: "Steering"
    value: "True"
  - 
    key: "Turn Signals"
    value: "False"
fault_status: 
  - 
    key: "Accelerator"
    value: "False"
  - 
    key: "Brakes"
    value: "False"
  - 
    key: "Headlights"
    value: "False"
  - 
    key: "Horn"
    value: "False"
  - 
    key: "Shifter"
    value: "False"
  - 
    key: "Steering"
    value: "False"
  - 
    key: "Turn Signals"
    value: "False"
---`
### Carma version where this issue was discovered

carma-system 3.7.2+
### Expected behavior
carma should not shut down
### Actual behavior

carma shuts down after few seconds without any error. UI sasys ssc failed
### Steps to reproduce the actual behavior

1. Do this
1. Then do this...

**Comment by msmcconnell** [comment]
Resolved by PR to private vehicle calibration repo
