### ISSUE TITLE
GStreamer Camera Driver for CARMA

### ISSUE THREAD

**Issue by GoodarzMehr** [usdot-fhwa-stol/carma-platform#1442]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [x] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

We have developed a GStreamer camera driver for CARMA that is available at [this](https://github.com/VT-ASIM-LAB/gstreamer_camera_driver/) repository. The driver is based on the ROS GSCam package that publishes images to a ROS topic from a GStreamer camera stream. The code has been modified to ensure it satisfies CARMA's requirements. Namely, that it publishes images in BGR8 encoding and that it also publishes a driver discovery message at 1.25 Hz. We would welcome your feedback on the driver, and if you find it useful, feel free to include it on the main CARMA repository.

### Carma version where this issue was discovered

N/A

### Expected behavior
N/A

### Actual behavior

N/A

### Steps to reproduce the actual behavior

N/A

### Related work

N/A

**Comment by msmcconnell** [comment]
This is great to see @GoodarzMehr ! We will definitely take a look an probably add a link to the repo in one of our documents.

**Comment by msmcconnell** [comment]
I took a quick look and it seems the driver is setup correctly to interface with carma-platform.

**Comment by GoodarzMehr** [comment]
It's great to hear that! We have also created hardware drivers for Ouster lidars and Inertial Labs GNSS products that we will be uploading soon, which should hopefully expand the hardware compatibility of the CARMA platform. We are also working on a Dataspeed interface driver that uses Dataspeed's own ULC controller which should remove the need for a separate proprietary software like AutonomouStuff's SSC.
