### ISSUE TITLE
Platooning_strategic plugin is segfaulting during workzone testing

### ISSUE THREAD

**Issue by MishkaMN** [usdot-fhwa-stol/carma-platform#1451]
### Types of Issue

- [X] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

This happens only when the car is crossing the stop_bar on the green light. The platooning_strategic plugin crashes with or without any nearby cars engaged, right when the car gets on "left merging" section of the road. Lowering its priority did not help
This doesn't prevent the carma-system from running successfully.

### Carma version where this issue was discovered

carma-system 3..7.2+ release/a1

### Expected behavior
platooning_strategic should not crash
### Actual behavior

See above.
### Steps to reproduce the actual behavior

1. Do this
1. Then do this...

**Comment by msmcconnell** [comment]
Testing suggests this was resolved by the above PR
