### ISSUE TITLE
Unavailable values found in generated BSM 

### ISSUE THREAD

**Issue by jwillmartin** [usdot-fhwa-stol/carma-platform#1478]
### Types of Issue

- [x ] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

Messages generated by CARMA Messenger contain the unavailable value for the following BSM core data fields:
- sec_mark
- accuracy
- transmission
- speed
- heading
- angle
- accelSet
- brakes

All fields were briefly tested on the Fusion to ensure unavailable values weren't the default output when the vehicle was stationary.

### Expected behavior
All noted fields should have actual values other than unavailable. 

### Actual behavior

Fields listed above are filled with unavailable values.

![image](https://user-images.githubusercontent.com/22165412/137023467-d449a69d-9f06-450d-b555-c69def9ac4f0.png)

**Comment by msmcconnell** [comment]
Resolved by above PR

**Comment by msmcconnell** [comment]
@lewisid Please provide details on reopen

**Comment by msmcconnell** [comment]
Seemingly resolved by above PR. Will close for now.
