### ISSUE TITLE
Need a proper way to handle trajectory re-plan in complex maneuver

### ISSUE THREAD

**Issue by qswawrq** [usdot-fhwa-stol/carma-platform#149]
Currently, if arbitrator got a notification on trajectory failure when it is running a complex maneuver, the speed change from the complex maneuver to a regular longitudinal is not handled. It might result in a max_accel deceleration from the current speed.

**Comment by darrelld05** [comment]
This issue was transferred from the original CARMAPlatform: Old issue # 744

**Comment by TonysCousin** [comment]
Only applies to Carma2 architecture, so this is now OBE.
