### ISSUE TITLE
Input vectors empty exception from cooperative lane change

### ISSUE THREAD

**Issue by adev4a** [usdot-fhwa-stol/carma-platform#1507]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

Sometimes towards the end of lane change the cooperative lane change plugin throws a Input Vectors are empty exception.

![CLC_exception](https://user-images.githubusercontent.com/51463994/139490373-eac22c2e-8de5-4094-bb46-c48ef3a7dd65.png)

### Carma version where this issue was discovered
3.8.2

### Expected behavior
Lane change should complete without exceptions
### Actual behavior

Close to the end of a lanechange carma crashes with this exception.
### Steps to reproduce the actual behavior

1. Run carma 3.8.2 on a route that requires a lane change.

**Comment by msmcconnell** [comment]
Seemingly resolved by above PR
