### ISSUE TITLE
Tracking did not work properly when it is tracking speed and downtrack distance

### ISSUE THREAD

**Issue by qswawrq** [usdot-fhwa-stol/carma-platform#151]
Tracking compares the current downtrack distance with a wrong number, which will show a wrong/large downtrack error. The same thing happened in tracking speed error. Something must be wrong in the logic of error tracking. Here is the log file:
[20180214-145722.txt](https://github.com/fhwa-saxton/CarmaPlatform/files/1725522/20180214-145722.txt)

**Comment by darrelld05** [comment]
This issue was transferred from the original CARMAPlatform: Old issue # 643

**Comment by TonysCousin** [comment]
Since this applies only to the Carma2 guidance architecture, it is now OBE.
