### ISSUE TITLE
MobilityPath and MobilityOperation header hostBSMId  are incorrect

### ISSUE THREAD

**Issue by dan-du-car** [usdot-fhwa-stol/carma-platform#1519]
### Types of Issue
Both MobilityPath and MobilityOperation header hostBSMId  are incorrect. The BSM id total length is 8, however both MobilityPath and MobilityOperation are sending 10 digits BSM id to cpp_message node. So cpp_message node will ignore this 10 digits bsm id and replace it with 8 digits default id = "00000000". 

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

 
-- This part should belong to the regional extension frame for --
-- the usage of mobility message. Due to the limitation of ASN1C, --
-- we put them in here for the temporary use. --
BSM id J2735 field type:
MobilityHeader ::= SEQUENCE {
   hostStaticId    MobilityStaticID,
   targetStaticId  MobilityStaticID,
   hostBSMId       MobilityDynamicID,
   planId          MobilityGUID,
   timestamp       MobilityTimestamp
}

MobilityDynamicID ::= IA5String (SIZE(8))
   -- mobility dynamic ID is the same as host vehicle current BSM ID in hex string

### Carma version where this issue was discovered

carma-3.8.2
### Expected behavior
Infrastructure shall receive correct BSM id from vehicle in MobilityPath (optional), MobilityOperation (required), and BSM (required) messages.

### Actual behavior

Infrastructure is receiving incorrect default BSM id = "00000000" from vehicle.

### Steps to reproduce the actual behavior
MobilityPath received from v2xhub:
![Mobilitypath_decode_sending_from_Fusion_engaged_vehicle_2](https://user-images.githubusercontent.com/62157949/140091628-85d71724-52a4-4a1b-84c5-c6bd90130d29.PNG)
MobilityPath sent from vehicle:
---
header: 
  sender_id: "DOT-45254"
  recipient_id: ''
  sender_bsm_id: "2405821416"
  plan_id: "e2c73d5b-c925-4f94-ac81-01f17d2a7d72"
  timestamp: 1635881411168
trajectory: 
  location: 
    ecef_x: 110456509
    ecef_y: -484207708
    ecef_z: 398843923
    timestamp: 0
  offsets: 
    - 
      offset_x: 31
      offset_y: 8
      offset_z: 0
    - 
      offset_x: 97
      offset_y: -2
      offset_z: -29
    - 
      offset_x: 97
      offset_y: -2
      offset_z: -28
    - 
      offset_x: 97
      offset_y: -1
      offset_z: -29
    - 
      offset_x: 98
      offset_y: -2
      offset_z: -28
    - 
      offset_x: 97
      offset_y: -1
      offset_z: -29
    - 
      offset_x: 97
      offset_y: -1
      offset_z: -28
    - 
      offset_x: 98
      offset_y: -2
      offset_z: -28
    - 
      offset_x: 97
      offset_y: -1
      offset_z: -29
    - 
      offset_x: 97
      offset_y: -2
      offset_z: -28
    - 
      offset_x: 97
      offset_y: -1
      offset_z: -29
    - 
      offset_x: 98
      offset_y: -2
      offset_z: -29
    - 
      offset_x: 97
      offset_y: -1
      offset_z: -28
    - 
      offset_x: 97
      offset_y: -2
      offset_z: -29
    - 
      offset_x: 97
      offset_y: -2
      offset_z: -29
    - 
      offset_x: 97
      offset_y: -2
      offset_z: -29
    - 
      offset_x: 97
      offset_y: -1
      offset_z: -29
    - 
      offset_x: 98
      offset_y: -2
      offset_z: -28
    - 
      offset_x: 97
      offset_y: -2
      offset_z: -29
    - 
      offset_x: 97
      offset_y: -1
      offset_z: -29
    - 
      offset_x: 97
      offset_y: -1
      offset_z: -28
    - 
      offset_x: 98
      offset_y: -2
      offset_z: -28
    - 
      offset_x: 97
      offset_y: -1
      offset_z: -28

N/A

**Comment by dan-du-car** [comment]
Please double check the J2735 BSM message VehicleSize.length value is converted to centimeters.
https://github.com/usdot-fhwa-stol/carma-messenger/blob/564833996efad24056cc1836a101640a84791d3b/carma-messenger-core/cpp_message/src/BSM_Message.cpp#L171

**Comment by msmcconnell** [comment]
This was resolved by above PRs
