### ISSUE TITLE
ILC 32-bit range exception due to nan speed in vehicle state sent from CLC

### ISSUE THREAD

**Issue by MishkaMN** [usdot-fhwa-stol/carma-platform#1521]
### Types of Issue

- [X] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

At ATEF, we were running into this "duration is out of 32-bit range" (from vehicle state having a speed of -nan in ILC logs) ~1-2 seconds after starting the lane change. From our experience, this could actually come from lane change's faulty logic as the state with erroneous speed can be sent to ILC through plan_delegator. 
inlanecruisingplugin
cooperativelanechangeplugin

### Carma version where this issue was discovered

release/elise (3.8.2+)
### Expected behavior
There should be no exception. And the speed should not be nan.

### Actual behavior

See above.

### Steps to reproduce the actual behavior

See above

**Comment by msmcconnell** [comment]
Resolved by above PR
