### ISSUE TITLE
CARMA should be configured to keep BSM ID consistent

### ISSUE THREAD

**Issue by lewisid** [usdot-fhwa-stol/carma-platform#1525]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [x] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

Carma simulation testing requires a way to keep track of bsm messages sent and received by specific vehicles. 

### Carma version where this issue was discovered

3.8.1

**Comment by msmcconnell** [comment]
Resolved by above PRs. ID can not be controlled by a vehicle calibration parameter.
