### ISSUE TITLE
Feature/signalized intersection

### ISSUE THREAD

**Issue by MishkaMN** [usdot-fhwa-stol/carma-platform#1528]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [X] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

SignalizedIntersection regulatory element must be implemented to support the signalized intersection. This task is to implement this class in lanelet_extension package in autoware.ai. World model and carma_wm_ctrl update portions are not included in the scope.

### Carma version where this issue was discovered

carma-system 3.8.2+ (autoware.ai)
### Expected behavior
See above, and Vector map is loadable/writable after including the intersection in XML syntax

### Actual behavior

NA

**Comment by msmcconnell** [comment]
Resolved by above PRs
