### ISSUE TITLE
TrafficLight should be renamed to TrafficSignal

### ISSUE THREAD

**Issue by MishkaMN** [usdot-fhwa-stol/carma-platform#1529]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [X] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

Upon client's request, the CarmaTrafficLight naming should be changed to CarmaTrafficSignal for better terminology.

### Carma version where this issue was discovered

carma-system 3.8.2 (but applies to previous versions as well)

### Expected behavior
See above.
### Actual behavior

NA

**Comment by msmcconnell** [comment]
Resolved by above PRs
