### ISSUE TITLE
Right turn issue from East to West at innovation drive

### ISSUE THREAD

**Issue by dan-du-car** [usdot-fhwa-stol/carma-platform#1581]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

The car is going into the intersection way in before it turns right.

### Carma version where this issue was discovered
carma-3.10.0

### Expected behavior
The car should follow the trajectory and curve line when it makes right turn when selecting the West destination route and turning right at the West intersection.

### Actual behavior

The car is going into the intersection way in before it turns right.

### Steps to reproduce the actual behavior

carma start all
select a West destination route and turn right.
Engage vehicle

**Comment by msmcconnell** [comment]
@dan-du-car This was due to a map issue correct? If so can we close this since its not an issue with the software system and just track it in Jira?
