### ISSUE TITLE
Signalized Intersection support in world model

### ISSUE THREAD

**Issue by MishkaMN** [usdot-fhwa-stol/carma-platform#1587]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [X] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

j2735 MAP and SPAT messages as well as world model should support CARMASignalizedIntersection objects. Especially this issue is to support dynamic SPAT timers.

### Carma version where this issue was discovered

carma-system:3.8.2+
### Expected behavior
SPAT timer is set. Another SPAT timer with different cycle should set another cycle.

### Actual behavior

NA
### Steps to reproduce the actual behavior

NA

**Comment by msmcconnell** [comment]
Resolved by above PRs
