### ISSUE TITLE
MAP.msg to lanelet objects conversion error handling improvement

### ISSUE THREAD

**Issue by MishkaMN** [usdot-fhwa-stol/carma-platform#1593]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [X] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

As first appeared in https://github.com/usdot-fhwa-stol/carma-platform/pull/1586, some previous error handling functions changed from throwing exception to simply logging warning signs. This change was added to better support testing and save time; however, either core issue of why exception being thrown needs to be resolved or there needs to be solid reason why it can stay this way.

### Carma version where this issue was discovered

carma-platform 3.10.0+

### Expected behavior
See above
### Actual behavior

See above
### Steps to reproduce the actual behavior

1. Do this
1. Then do this...

**Comment by msmcconnell** [comment]
Resolved by above PR
