### ISSUE TITLE
Signalized Intersection Strategic Plugin

### ISSUE THREAD

**Issue by MishkaMN** [usdot-fhwa-stol/carma-platform#1612]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [X] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

In order to fully finish implementing TSMO UC 2. Signalized intersection strategic plugin is required. 
This plugin should
- decide whether to stop or go based on the SPAT info.
- activate trajectory smoothing algorithm if the vehicle can make it through green signal.

### Carma version where this issue was discovered

carma-system 3.11.0+
### Expected behavior
See above.

### Actual behavior

NA

**Comment by msmcconnell** [comment]
This was released in carma-system-4.0
