### ISSUE TITLE
Compiler warnings in carma_wm

### ISSUE THREAD

**Issue by TonysCousin** [usdot-fhwa-stol/carma-platform#1677]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

During routine compiles of carma_wm there are lots of warnings generated.  Many of the problems identified are innocuous (e.g. extra semi-colon), but they clutter the output making real problems difficult to see.  As a result, real problem are being overlooked.  Some of these warnings point out legitimate code defects that need to be fixed.

### Carma version where this issue was discovered

Develop after version 3.11.0

### Expected behavior
Code compiles with no warning or info messages.

### Actual behavior

A large number of warnings appear during compile.

### Steps to reproduce the actual behavior

1. Run the build script for carma-platform

**Comment by msmcconnell** [comment]
Resolved by above PR
