### ISSUE TITLE
carma-messenger is unable to process incoming TCM binary from V2XHub

### ISSUE THREAD

**Issue by JonSmet** [usdot-fhwa-stol/carma-platform#1681]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

Carma-messenger is unable to process TCMs received from V2XHub. These TCMs are received by the vehicle's OBU and forwarded to the Spectra PC over ethernet, where they are processed by carma-messenger. 

Carma-messenger's cpp_message node logs the following error when attempting to process the received TCM:
`1647284790.8286116 [carma_component_container_mt-7] 1647284790.827886098 | WARN | inbound_binary_callback:92 | Cannot decode geofence control message.`

Since the cpp_message node is unable to process the message, no geofence ever gets published onto the carma system's /message/incoming_geofence_control topic.

### Carma version where this issue was discovered

Jetta/Gillet Candidate Release

### Expected behavior
The incoming TCM binary is processed by cpp_message, and the contents of the TCM are published onto the carma system's /message/incoming_geofence_control topic.

### Actual behavior

The cpp_message node is unable to process the incoming TCM binary.

### Steps to reproduce the actual behavior

1. Launch carma
2. Select a route and broadcast TCR
3. Receive TCM(s) from V2XHub

**Comment by msmcconnell** [comment]
Resolved by above PR
