### ISSUE TITLE
Twist Filter node ms to mph speed limit 

### ISSUE THREAD

**Issue by MishkaMN** [usdot-fhwa-stol/carma-platform#1689]
### Types of Issue

- [X] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

Twist filter node is expecting m/s configurable speed limit. However currently the config specifies it as mph and rest of the system expects mph (internally converting it to m/s). Therefore, twist filter node needs to to expect mph now.

### Expected behavior
speed limit should be capped at desired mph speed from `carma config edit`

### Actual behavior

speed limit is set in m/s so it doesn't limit it.

### Steps to reproduce the actual behavior

Run carma with any high speed

**Comment by msmcconnell** [comment]
Resolved by above PR
