### ISSUE TITLE
Compiler warnings in basic_autonomy

### ISSUE THREAD

**Issue by TonysCousin** [usdot-fhwa-stol/carma-platform#1694]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

During routine compiles of this package, there are lots of warnings generated. Many of the problems identified are innocuous (e.g. extra semi-colon), but they clutter the output making real problems difficult to see. As a result, real problem may be overlooked.

### Carma version where this issue was discovered

Develop branch after v3.11.0

### Expected behavior
Package builds with no compiler messages.

### Actual behavior

Lots of warnings and notes from the compiler due to improper or ineffective use of the C++ language.

### Steps to reproduce the actual behavior

Build the package using colcon.

**Comment by msmcconnell** [comment]
Resolved by above PR
