### ISSUE TITLE
Lidar fault not following expected fault map on trucks in 4.0.2

### ISSUE THREAD

**Issue by msmcconnell** [usdot-fhwa-stol/carma-platform#1723]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

When executing a test of the ACE sensor failure behavior as a regression test in the 4.0.2 release. The following issue was observed by the test engineer
"deactivate the lidar, then gps.  When I turned off the first lidar during a run, after a second passed, the carma UI showed an SSC failure."

This does not match the output expected by the sensor failure behavior. 
### Carma version where this issue was discovered

4.0.2
### Expected behavior
Single lidar failure results in a caution. Both lidar failures result in a warning followed by switching to GPS. 1 message per caution can be seen on UI.
### Actual behavior

UI showed exception SSC Failed
### Steps to reproduce the actual behavior

See description

**Comment by TonysCousin** [comment]
I scanned through the health monitor code to get a sense of what might be happening. No firm conclusions, but here are some thoughts for whoever might pick this up.  I'm happy to help, but will be unavailable on Wed.
* I am looking at code tagged as v4.0.0 (master commit 33e66df4 from Apr 11).  This issue says v4.0.2, but I don't know where that comes from or what the diffs might be (no such tag in carma-platform).  Guessing it refers to changes in other repos.
* Obvious question:  is it plugged in?  I.e. does the truck identify itself as a truck, and are the 2 lidars and gps listed in that order under the vehicle parameters lidar_gps_drivers?
* DriverManager::update_driver_status() generates a fake_entry that is never used.  It seems there's some missing logic to test if it is a lidar, then to send this to em_.update_entry().  This certainly looks like it could be the problem.
* The Entry struct has a constructor defined that takes in args but never uses an initializer list to copy these arg values to its member variables.  This may be a shortcoming in my understanding of C++, but I don't see how any entries can even be defined this way.
