### ISSUE TITLE
strategic plugin updates for UC3 to lci_strategic_plugin

### ISSUE THREAD

**Issue by aswath1** [usdot-fhwa-stol/carma-platform#1762]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [x] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

For TSMO Use Case 3, CARMA Streets will be providing a schedule message to CARMA Platform containing the entry time for the signalized intersection the vehicle plans to traverse. This task is to formalize the design for what those code changes will entail. The expectation is that the existing lci_strategic_plugin can be updated so that it uses the schedule from the intersection for setting its ET algorithm parameters instead of computing them based on spat if the message is available. If the message is not available, the existing logic should be executed to compute these values. 
### Steps to reproduce the actual behavior

1. Do this
1. Then do this...

**Comment by msmcconnell** [comment]
Resolved by above PR
