### ISSUE TITLE
Remove Interface Mgr Driver Discovery Capability

### ISSUE THREAD

**Issue by qswawrq** [usdot-fhwa-stol/carma-platform#177]
### Descriptive summary
As a Carma developer, I depend on the code being as lean an maintainable as possible. Modify legacy Carma consumer nodes to use the modified CARMA3 API instead of using Interface Manager for driver discovery.
### Expected behavior
CARMA nodes connect to drivers directly without going through Interface Manager.
### Actual behavior
Some CARMA nodes are using Interface Manager get_driver_capabilities service.
### Steps to reproduce the behavior
N/A
### Related work
N/A

**Comment by msmcconnell** [comment]
@qswawrq Is this still an issue?

**Comment by qswawrq** [comment]
Yup. We did not start working on it.

**Comment by TonysCousin** [comment]
This issue is now OBE due to new structure and API provided by Health Monitor, which replaces Interface Manager.
