### ISSUE TITLE
MobilityResponse message not using cav_msgs/PlanType, as it should to match the MobilityRequest message

### ISSUE THREAD

**Issue by afrye-leidos** [usdot-fhwa-stol/carma-platform#1775]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

When adding fields to the MobilityResponse message, it was updated to use the new MobilityPlanType message, instead of the old PlanType message. This is unintended and causes a message mismatch.

The solution is to remove the new MobilityPlanType message, and instead add its new enum fields to the PlanType message, also updating the cpp_message file and relevant unit tests. These changes for both cav_msgs and carma_v2x_msgs. 

### Steps to reproduce the actual behavior

1. Do this
1. Then do this...

**Comment by msmcconnell** [comment]
Resolved by above PRs
