### ISSUE TITLE
Convert carma_wm_ctrl to ros2

### ISSUE THREAD

**Issue by MishkaMN** [usdot-fhwa-stol/carma-platform#1793]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [X] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

Convert carma_wm_ctrl to ros2.

### Carma version where this issue was discovered

carma-system-4.0.3+
### Expected behavior
carma_wm_ctrl should work with ROS2

### Actual behavior

NA
### Steps to reproduce the actual behavior

1. Do this
1. Then do this...

**Comment by msmcconnell** [comment]
Resolved by above PRs
