### ISSUE TITLE
Segfault in getAffectedLaneletOrAreas

### ISSUE THREAD

**Issue by MishkaMN** [usdot-fhwa-stol/carma-platform#1794]
### Types of Issue

- [X] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

During UC2 testing, to support MAP msg to osm map conversion, getAffectedLaneletOrAreas function was modified such that a lanelet can still be detected even if there is only 1 point in it if there was previous plenty previous points indicating its direction. See https://github.com/usdot-fhwa-stol/carma-platform/pull/1764

However, there is an edge case where it could segfault if there is only really only 1 point in the list, which needs to be guarded against.

### Expected behavior
Carma should not crash if it detected geofence ( getAffectedLaneletOrAreas) with only 1 point.

### Actual behavior

Carma crashes if getAffectedLaneletOrAreas input has 1 point.

### Steps to reproduce the actual behavior

1. Do this
1. Then do this...

**Comment by msmcconnell** [comment]
Resolved by above PR
