### ISSUE TITLE
Dynamic Spat Processing with multiple phases 

### ISSUE THREAD

**Issue by aswath1** [usdot-fhwa-stol/carma-platform#1806]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [x] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

For TSMO Use Case 3, CARMA Streets will be providing a schedule message to CARMA Platform containing the entry time for the signalized intersection the vehicle plans to traverse. This task is to update world model package to process new SPAT message.
### Steps to reproduce the actual behavior

1. Do this
1. Then do this...

**Comment by msmcconnell** [comment]
Resolved by above #1803
