### ISSUE TITLE
Convert Plan Delegator to ROS2

### ISSUE THREAD

**Issue by MishkaMN** [usdot-fhwa-stol/carma-platform#1817]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [X] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

Convert plan delegator to ROS2

### Carma version where this issue was discovered

carma-system:4.1.0+

### Expected behavior
NA
### Actual behavior

NA
### Steps to reproduce the actual behavior

NA

**Comment by msmcconnell** [comment]
Resolved by above PR
