### ISSUE TITLE
Fix "too many arguments" warning in carma-base entrypoint.sh script

### ISSUE THREAD

**Issue by willcmartin** [usdot-fhwa-stol/carma-platform#1829]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

When building carma-platform from a `docker-compose.yml` carma-config script, a `[: too many arguments` warning is thrown. 

This is because the `entrypoint.sh` script in carma-base should check for _any_ command-line arguments. The current script throws `[: too many arguments` warning when more than one command-line argument is passed.

More than one command-line argument is passed when the `command:` property in the `docker-compose.yml` script that creates this docker image is longer than one word. For example `command: bash -c 'wait-for-it.sh localhost:11311 -- roslaunch /opt/carma/vehicle/config/carma_docker.launch'` in `carma-config/carla_integration/docker-compose.yml`

### Carma version where this issue was discovered

develop

### Expected behavior

No warnings should be thrown when more than one command-line argument is passed to `carma-base/entrypoint.sh`.

### Actual behavior

A `[: too many arguments` warning is given when more than one command-line argument is passed to `carma-base/entrypoint.sh`.

### Steps to reproduce the actual behavior

1. Install carma-platform
2. Build a carma-config docker image (I am using [this one](https://github.com/usdot-fhwa-stol/carma-config/tree/develop/carla_integration))
3. Set carma-platform config
4. `carma start all`

### Related work

Fixed with [this PR](https://github.com/usdot-fhwa-stol/carma-base/pull/125)

**Comment by msmcconnell** [comment]
Resolved by above PR
