### ISSUE TITLE
Port Arbitrator Node to ROS2

### ISSUE THREAD

**Issue by MishkaMN** [usdot-fhwa-stol/carma-platform#1832]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [x] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

To support ROS2 migration, the arbitrator node needs to be ported to ROS2.

### Carma version where this issue was discovered

carma-system:4.1.0+

### Expected behavior
N/A

### Actual behavior

N/A

### Steps to reproduce the actual behavior

N/A

### Related work
N/A

**Comment by msmcconnell** [comment]
Resolved by above PR
