### ISSUE TITLE
Port the trajectory_visualizer node from ROS1 to ROS2  

### ISSUE THREAD

**Issue by aswath1** [usdot-fhwa-stol/carma-platform#1845]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [x] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

Port the trajectory_visualizer node from ROS1 to ROS2

The result of this story should be this nodes fully ported and integrated into the launch system
### Steps to reproduce the actual behavior

1. Do this
1. Then do this...

**Comment by msmcconnell** [comment]
Resolved by above PR
