### ISSUE TITLE
Integration test of ROS2 Guidance package nodes: Arbitrator, Plan Delegator, and Trajectory Executor

### ISSUE THREAD

**Issue by MishkaMN** [usdot-fhwa-stol/carma-platform#1854]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [X] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

Integration test of ROS2 Guidance package nodes: Arbitrator, Plan Delegator, and Trajectory Executor. Vehicle should be able initialize CARMA, select a route, and the ROS2 Guidance package nodes should be able to begin planning and trajectory generation in coordination with ROS1 Plugins. Test should be conducted at TFHRC using a basic route to demonstrate functionality. Plugins to be included in test should be the ROS1 versions of Route Following, ILC, and Pure Pursuit Control. These plugins will be tested in their ROS2 port under a separate integration test story.

### Expected behavior
Vehicle is able to make a simple travel at TFHRC.

### Actual behavior

NA
### Steps to reproduce the actual behavior

NA

**Comment by msmcconnell** [comment]
Resolved by above PR
