### ISSUE TITLE
Vehicle not able to lane change on a merge lane

### ISSUE THREAD

**Issue by saina-ramyar** [usdot-fhwa-stol/carma-platform#1862]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

During the verification test of release/cabin it was found that a vehicle trying to lane change to join a platoon in the adjacent lane cannot generate trajectories, and drifts out of the lane

### Expected behavior
vehicle complete driving on the merge lane and join the platoon on the adjacent lane
### Actual behavior

vehicle stops generating trajectories in the middle of the merge lane and swerves out of the way.

### Steps to reproduce the actual behavior

1. start a vehicle in a merge lane
2. have a platoon of vehicles on the lane adjacent to the merge
3. run all the cars so the solo vehicle tries to join the platoon

**Comment by msmcconnell** [comment]
Resolved by above PR
