### ISSUE TITLE
Basic Autonomy ignores defined maneuvers for lane following

### ISSUE THREAD

**Issue by saina-ramyar** [usdot-fhwa-stol/carma-platform#1863]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [x] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

During integration test of release/cabin, it was found out that the basic autonomy library ignores the lanelets defined in the `lane_ids` field of the maneuver message, and generates a list of following lanelets using the `getLaneletsBetween` method from WM.
The problem with this approach is that shortestPath is used to generate the list of lanelets, which is not desirable for some use cases such as platooning.

A partial fix is implemented in this branch: fix/BA_lanelet_list
### Carma version where this issue was discovered

integration test of release/cabin
### Expected behavior
basic_autonomy uses lanelets defined in the maneuver msg to generate trajectories.
### Actual behavior

 basic autonomy library ignores the lanelets defined in the `lane_ids` field of the maneuver message, and generates a list of following lanelets using the `getLaneletsBetween` method from WM.
### Steps to reproduce the actual behavior

1. Do this
1. Then do this...

**Comment by msmcconnell** [comment]
Above linked commit contains code which needs to be updated when resolving this issue

**Comment by msmcconnell** [comment]
Resolved by above PRs
