### ISSUE TITLE
Switch ROS1 ros_bridge with ROS2

### ISSUE THREAD

**Issue by aswath1** [usdot-fhwa-stol/carma-platform#1882]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [x] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

Switch ROS1 ros_bridge with ROS2
### Steps to reproduce the actual behavior

1. Do this
1. Then do this...

**Comment by msmcconnell** [comment]
Resolved through combination of #1881 and https://github.com/usdot-fhwa-stol/carma-platform/issues/1896
