### ISSUE TITLE
The 'carma' package build fails due to error in its CmakeLists.txt

### ISSUE THREAD

**Issue by JonSmet** [usdot-fhwa-stol/carma-platform#1900]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

When building carma-platform, the 'carma' package build fails since the CMakeLists.txt references a 'ui' directory, which does not currently exist in the package.

### Carma version where this issue was discovered

Develop (August 22nd, 2022)

### Expected behavior
carma-platform is able to build successfully

### Actual behavior

The build fails during the build of the carma package

### Steps to reproduce the actual behavior

1. Attempt to build carma-platform via the build-image.sh script
2. Observe a build error due to the 'carma' package

**Comment by msmcconnell** [comment]
Resolved by above PR
