### ISSUE TITLE
Trajectory Visualizer throws an exception after engaging

### ISSUE THREAD

**Issue by saina-ramyar** [usdot-fhwa-stol/carma-platform#1909]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

When the vehicle is engaged, after moving for about 2 meters, CARMA fails with an uncaught exception from the Trajectory Visualizer node as follows:
Uncaught Exception from node: trajectory_visualizer_node exception: cannot store a negative time point in rclcpp::Time while in ACTIVE state.
### Carma version where this issue was discovered
develop

### Expected behavior
Trajectory visualizer does not throw an exception 
### Actual behavior

When the vehicle is engaged, after moving for about 2 meters, CARMA fails with an uncaught exception from the Trajectory Visualizer node
### Steps to reproduce the actual behavior

1. carma start all
2. localize
3. select a route
4. engage

**Comment by msmcconnell** [comment]
Resolved by above PR
