### ISSUE TITLE
Port pure pursuit to ROS2

### ISSUE THREAD

**Issue by MishkaMN** [usdot-fhwa-stol/carma-platform#1928]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [X] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

Port pure pursuit to ROS2
### Carma version where this issue was discovered
carma-systems:4.2.0+ develop

**Comment by msmcconnell** [comment]
Resolved by above PRs
