### ISSUE TITLE
carma platoon container is duplicated in launch file ROS2

### ISSUE THREAD

**Issue by MishkaMN** [usdot-fhwa-stol/carma-platform#1933]
### Types of Issue

- [X] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

See below. Platoon container is duplicated

https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/carma/launch/plugins.launch.py#L277-L399

### Carma version where this issue was discovered

carma-system-4.2.0+ develop
### Expected behavior
Should be one container
### Actual behavior

See above
### Steps to reproduce the actual behavior

1. Do this
1. Then do this...

**Comment by msmcconnell** [comment]
Resolved by above PR
