### ISSUE TITLE
Spectra PC is slow in general for all vehicles

### ISSUE THREAD

**Issue by MishkaMN** [usdot-fhwa-stol/carma-platform#1935]
### Types of Issue

- [X] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

The PC appear to be slow when operating carma on most vehicles, especially when running rviz with pcd map and lidar.  Instances where they occur differ from vehicle to vehicle:
- White Pacifica: Just running carma in general makes the pc slow. Run basic travel with pcd, rviz and lidar running, and observe if mouse is not smooth or opening folders and logs.
- Black Pacifica: It is better than most, but when running carma, switching back to main terminal would freeze the pc for a few seconds.
- Silver Lexus: It was the slowest. 1) Turning on the car was taking really long time for ubuntu to boot (once took 10min). Restarted the pc to make it boot up if it was taking too long. 2) I could hear the crystal computer restarting every 15-20min, and that maybe slowing down. However, also it took longer than usual for localization_manager was ready to localize (5min) and takes more tries to have the localization to lock compared to for example Blue Lexus (a.k.a the automatic localization shift seem slow and not "sticky")
- Blue Lexus: Did not notice much slow down.
- Fusion: did not test.

It is believed that White Pacifica has more processing power than other PC, but yet to experience similar slow-down which possibly indicate it could be the carma itself that is slowing things. So the developer should investigate if that is the case.

### Carma version where this issue was discovered

carma-system-4.2.0+ develop
### Expected behavior
- PC should not experience slow down/ freezing when switching terminals/ opening folders such as logs/ or in general.
- NDT matching startup should not take longer than 2-3min (this could be wrong), and the shift should happen fast and stick to the environment (as opposed to drifting slowly/shifting to wrong direction/not sticking etc). 

### Actual behavior

See above.
### Steps to reproduce the actual behavior

1. Start carma on develop
2. Make sure pcd is loaded and NDT matching configured to run (notice if there is slowdown when it happens)
3. Measure how long it takes for NDT to startup.
4. See if there is any delay or trouble in localization
5. Try opening /opt/carma/logs and see if it is slow.
6. Run carma few times, listen to different topics on a different terminals, and switch to the main terminal to see if texts are still printing (it goes blank unless stopping carma) and not freeze the mouse

**Comment by msmcconnell** [comment]
Closing as PC's are being updated and these issues have not been consistent at all.
