### ISSUE TITLE
Lane following trajectory is not using correct lanelet

### ISSUE THREAD

**Issue by MishkaMN** [usdot-fhwa-stol/carma-platform#1943]
### Types of Issue

- [X] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

From the trajectory visualizer, it was noticed that the trajectory being generated for simple lane following looks like a weird curved trajectory. It is assumed that a different lanelet is being used other than the ones on route. Since inlanecruising_plugin uses basic_autonomy_ros2, most likely some lane_ids related specification is wrong there. Once the vehicle enters into intersection, despite a small swerve towards original direction, it gets back on track generating correct trajectory

![image](https://user-images.githubusercontent.com/20613282/191837270-f8ea7304-62f9-42d6-a0ee-b505f3d728f4.png)
![image](https://user-images.githubusercontent.com/20613282/191837371-6e27f8d6-a97c-46a1-8995-38019fe9647b.png)
![image](https://user-images.githubusercontent.com/20613282/191837416-f38583e5-5a66-4fbf-86ed-d66ca3fa98c3.png)

### Carma version where this issue was discovered

carma-system-4.2.0 develop+
### Expected behavior
Generate trajectory along route for lane following
### Actual behavior

See pics
### Steps to reproduce the actual behavior

Do normal operation

**Comment by msmcconnell** [comment]
Resolved by above PRs
