### ISSUE TITLE
lci_strategic_plugin should be able to plan for entry time outside available signal states (UC3)

### ISSUE THREAD

**Issue by MishkaMN** [usdot-fhwa-stol/carma-platform#1947]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [X] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

- Current implementation in lci_strategic_plugin has its carma-street strategy parameter processing turned off. It should be turned on when carma-street is available.
- Also the plugin's current implementation makes the vehicle cruise at minimum speed and expect to stop until given ET by carma-street is within available future_event_list. However, the intended design of UC3 is to plan trajectory smoothing solely based on the ET by carma-street either way. And only consider future_event_list for safety concern once it is available. 

### Carma version where this issue was discovered

carma-system:4.2.0+ develop
### Expected behavior
See above.
### Actual behavior

NA
### Steps to reproduce the actual behavior

NA

**Comment by msmcconnell** [comment]
Resolved by above PRs
