### ISSUE TITLE
Arbitrator not subscribed to vehicle speed & wrong frequency

### ISSUE THREAD

**Issue by MishkaMN** [usdot-fhwa-stol/carma-platform#1959]
### Types of Issue

- [X] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

After conversion to ROS2, it was found that arbitrator was not subscribing to current velocity of the vehicle which gives incorrect initial speed to the strategic plugins. 

Also arbitrator is planning at 0.5hz as opposed to 10hz because the state machine sequence goes PLANNING -> WAITING -> PLANNING. State machine is called every 1hz, but due to the WAITING state in between the PLANNING states, it slows down the planning.

### Carma version where this issue was discovered

carma-system-4.2.0+ develop
### Expected behavior
Arbitrator should subscribe to current_speed
Arbitrator should call strategic plugins at 10hz

### Actual behavior

See above. 
### Steps to reproduce the actual behavior

See above.

**Comment by msmcconnell** [comment]
Resolved by above PR
