### ISSUE TITLE
One of the node in carma_guidance_container is failing silently

### ISSUE THREAD

**Issue by MishkaMN** [usdot-fhwa-stol/carma-platform#1961]
### Types of Issue

- [X] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

During integration testing of UC3, it was noticed that the carma_guidance_container would fail during mid-run. Currently it is not clear whether if it happens only UC3 scenarios (perhaps lci plugins could be sending corrupted data to guidance nodes and crashing them despite not crashing themselves). mobility_path_visualizer, trajectory_visualizer, port_dreyage_plugins were ruled out as culprits as they were turned off during test runs. It is suspected to be one of the required nodes such as arbitrator, plan_delegator, or trajectory_executor. This error shows up before failing:

` | [carma_component_container_mt-11] 1666034819.992949401 | ERROR | dequeue:77 | Calling dequeue on empty intra-process buffer
platform_ros2              | [carma_component_container_mt-11] terminate called after throwing an instance of 'std::runtime_error'
platform_ros2              | [carma_component_container_mt-11]   what():  Calling dequeue on empty intra-process buffer`

### Carma version where this issue was discovered

carma-system-4.2.0 develop+
### Expected behavior
carma_guidance_container does not fail

### Actual behavior

See above.

### Steps to reproduce the actual behavior

While UC3 MAP/SPAT/MobilityOperation is broadcasting. Engage carma with route selected towards EAST_DEST (intersection) starting from middle of innovation drive in between the intersection on TFHRC.

**Comment by msmcconnell** [comment]
Resolved by above PR though underlying issue was a ROS2 bug (see PR for details)
