### ISSUE TITLE
Add intersection data to status and intent messages broadcasted by carma-platform

### ISSUE THREAD

**Issue by MishkaMN** [usdot-fhwa-stol/carma-platform#1962]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [X] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

It was requested to add which intersection the status and intent messages are being broadcasted for from carma-platform during UC3. This does not mean lci plugins should be able to handle multiple intersections just yet. 

### Carma version where this issue was discovered

carma-system-4.2.0 develop+

### Expected behavior
In mobility operation, intersection id should be added. 

### Actual behavior

See above.

**Comment by msmcconnell** [comment]
Resolved by above PRs
