### ISSUE TITLE
LCI strategic plugin should detect next available green signal phase if current ET is not green with certainty

### ISSUE THREAD

**Issue by MishkaMN** [usdot-fhwa-stol/carma-platform#1963]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [X] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

In UC3, LCI strategic plugin checks whether if ET sent by carma-street is within green phase sent by SPAT with certainty (meaning inside modified interval reduces by green_buffer seconds parameter from each bound). If it falls inside the ending bound and within that green buffer, carma-platform should at least search for next available green phase signal and pick new ET at the start of the green buffer adjusted green phase. Current implementation of lci makes the car cruise and stop (case 8) if such case happens.

However, in theory this scenario can be avoided by carma-street sending ET that is always within the green_buffer adjusted interval.

Full algorithm related to modifying ET based on green signal and its buffer looks like this:

... the safety check shall go through the fixed phases in the modified spat, starting from the current phase. Then, the safety algorithm find the phase that has (start_time < ET and ET < end_time) or (ET > last phase end_time [called TBD area]).
- If this phase is red for the vehicle, then safety fails and I guess you can throw exception.
- If the phase is green, then
   - If ET < start_time + green_buffer, set ET to start_time + green_buffer
   - If ET > end_time - green_buffer, try to find the next green phase. If found, set ET to the start_time of the next green found + green_buffer. If not found, set it to last phase end_time (start_time of TBD area) + green_buffer
- If ET > last phase end_time (ET is within TBD area), just make sure ET > last phase end_time + green buffer. The TBD area doesn't have end_time.
Finally, find the trajectory case based on the modified safe ET..

### Carma version where this issue was discovered

carma-system-4.2.0+ develop

### Expected behavior
See above.

### Actual behavior

See above.

**Comment by msmcconnell** [comment]
Resolved by above PR
