### ISSUE TITLE
carma_platform is not able to handle dynamic states with only 1 future event

### ISSUE THREAD

**Issue by MishkaMN** [usdot-fhwa-stol/carma-platform#1976]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [x] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

During UC3 integration testing, it was discovered that carma-platform relies on 2 or more future events in the SPAT message to determine it is dynamic SPAT. Ideally it should also consider mobility operation message correlated to that SPAT to make a decision.

Since MOBOP message for UC3 is only processed by lci_strategic_plugin and SPAT is processed by carma_wm, there is no communication between the two at the moment, which is why carma_wm is not able to determine dynamic spat if it has only 1 future event.

### Carma version where this issue was discovered

develop after 4.2
### Expected behavior
platform is able to process 1 future event and do not crash

### Actual behavior

See description
### Steps to reproduce the actual behavior

Start carma with SPAT of only 1 future event, and it should crash

**Comment by msmcconnell** [comment]
Resolved by https://github.com/usdot-fhwa-stol/carma-platform/pull/1983
