### ISSUE TITLE
PidControllerTest fails on CI environment

### ISSUE THREAD

**Issue by qswawrq** [usdot-fhwa-stol/carma-platform#198]
### Descriptive summary
PidControllerTest unit test failed on CI environment once or twice (very rare).
### Expected behavior
All unit test should pass deterministically.
### Actual behavior
PidControllerTest might fail in some rare cases.
### Steps to reproduce the behavior
Hard to reproduce. If you run CI build for many times, it might show up.
### Related work
#184 
Both unit tests depend on system time. It causes some issues on Circle CI environment.

**Comment by TonysCousin** [comment]
Associated user story CAR-444 has been closed out since this only applies to Cadillacs, which are at end of life.  Need to consider whether this anomaly report should also be closed.

**Comment by TonysCousin** [comment]
No plans to further support Cadillacs, so closing this as OBE.
