### ISSUE TITLE
Edge cases in UC3 ET logic

### ISSUE THREAD

**Issue by aswath1** [usdot-fhwa-stol/carma-platform#1982]
### Types of Issue

- [X] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

In lci plugin's ET logic, 2 edge cases should be considered. 

1. There is a check that verifies if the received ET is within a green phase or TBD area or not. This check is not implemented correctly. It is possible that the ET is within a red or yellow phase, but the check is satisfied and returns true (meaning ET is within green or TBD).
(Following logic should account for a case where ET can be erroneously inside the future states. In which case, the vehicle should notify the user since carma-street is not supposed to send ET that is within RED. The current behavior of "cruising until stop" can be kept the same.)

![image](https://user-images.githubusercontent.com/32398753/206007301-7257299e-3823-4399-a7d1-2cd2b29d5f71.png)

2. If ET is within green and [ET-Green_Buffer] is not within green (i.e., ET is between the start time of the green and the start time plus green buffer), then there is a logic that changes ET such that [ET-Green_Buffer] is also within green. This check is not implemented correctly either.
(Following logic's intention is to increase ET to match the green_start + green_buffer if ET is within green buffer. However it is not clear if it is exactly working that way or the comments can be better. Additionally, this logic would fail if there are more than 2 GREEN phases in the SPAT as it utilizes current time instead of ET to determine which green it is closest to.)

![image](https://user-images.githubusercontent.com/32398753/206008951-0aba4306-cc9e-472e-9acf-56d82ab8daff.png)

Here is the pseudocodes of the existing and proposed Logic:

[LCI_Plugin_ET_Logic_V2.docx](https://github.com/usdot-fhwa-stol/carma-platform/files/10196135/LCI_Plugin_ET_Logic_V2.docx)

### Carma version where this issue was discovered

carma-system-4.2.0+ (develop)

### Expected behavior
See above.
### Actual behavior

See above.

**Comment by MishkaMN** [comment]
Resolved by above PR
