### ISSUE TITLE
The vehicle was stopping at the red SPAT but fails to move when it turns green spat.

### ISSUE THREAD

**Issue by aswath1** [usdot-fhwa-stol/carma-platform#1984]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary
The vehicle was stopping at the red SPAT but fails to move when it turns green spat. CARMA Worldmodel dynamic spat processing was not over righting the new spat received.

### Carma version where this issue was discovered
develop after 4.2

### Expected behavior
Spat data from streets can be used without issue.
### Actual behavior

See description
### Steps to reproduce the actual behavior

1. Do this
1. Then do this...
Try to test adaptive signal timing in carma streets with CARMA Platform

**Comment by msmcconnell** [comment]
Resolved by above PRs
