### ISSUE TITLE
UC3 LCI_Plugin HandleFailureCase Logic Bug

### ISSUE THREAD

**Issue by Saeid-Solei** [usdot-fhwa-stol/carma-platform#1985]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

In LCI Plugin, given an ET, the vehicle will first find a smoothed trajectory for itself (trajectory cases 1-8). Once the trajectory case is initially determined, the logic has some checks to decide its action and desired speed. One of the cases is called HandleFailureCase() which will be triggered if the vehicle was following a trajectory case previously and suddenly its ET becomes out of reach when the vehicle is close to the intersection and its distance to the stop bar is less than the safe stopping speed. In this case, since the vehicle is not able to stop at the stop bar with the max comfortable deceleration rate, HandleFailureCase() tells the vehicle to try to accelerate\decelerate to enter the intersection box with a speed close to the departure speed. 

There are two main scenarios that might trigger HandleFailureCase(). 
1. The vehicle ET is at the beginning of the green and the vehicle gets closer to the intersection that it should be based on its smoothed trajectory. In this case, the vehicle must slow down to allow the signal to change from red to green before entering the intersection box.
2. The vehicle ET is at the end of the green and as the vehicle gets closer to the intersection box, due to inaccuracy in trajectory control, the vehicle receives an ET that is pushed back to the beginning of the next green.

While the current logic might work for the second case (we can hope that if the vehicle continues with its previous plan and accelerate, it can enter the intersection box during the end of the green or the yellow change phase), it does not make much sense for the first case (if the vehicle is trying to enter the intersection box at the beginning of a green, but it is closer than it should be, it should not accelerate to enter the intersection box. Instead, it should try to slow down to allow the signal light to change from red to green). This logic is the cause of some failed test runs where the vehicle enters the intersection box before the light change from red to green, or after the end of the green and during yellow change\red clearance.

To fix this issue, a new logic has been proposed. The proposed logic does not blindly tell the vehicle to accelerate. Instead, it will check if it can enter the intersection box during a green if it accelerate or decelerate or not. If it can follow any of these two trajectories and enter the intersection box during a green, it will follow the chosen trajectory. If it cannot in both cases, the vehicle will check if it can stop with an emergency deceleration rate. If yes, the vehicle will try to stop. If it cannot, it will throw exception and the test will fail. 

[LCI_Plugin_HandleFailure_Logic_Enhancement.docx](https://github.com/usdot-fhwa-stol/carma-platform/files/10196358/LCI_Plugin_HandleFailure_Logic_Enhancement.docx)

### Carma version where this issue was discovered

4.2.0

### Expected behavior
The vehicle shall not enter the intersection box before the signal light change from red to green or after the green has ended.

### Actual behavior

In some test runs, the vehicle enters a little early and before the signal light change from red to green.

**Comment by MishkaMN** [comment]
The suggested logic is implemented and merged in the PR
