### ISSUE TITLE
light_controlled_intersection_tactical_plugin exception: cannot store a negative time point in rclcpp::Time while in ACTIVE state.

### ISSUE THREAD

**Issue by aswath1** [usdot-fhwa-stol/carma-platform#1986]
### Types of Issue

- [X] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

platform_ros2              | [carma_component_container_mt-17] 1670528425.558134162 | ERROR | on_error:120 | Uncaught Exception from node: light_controlled_intersection_tactical_plugin exception: cannot store a negative time point in rclcpp::Time while in ACTIVE state.
platform_ros2              | [carma_component_container_mt-17] 1670528425.559358903 | ERROR | on_error:134 | Sent on_error system alert

### Carma version where this issue was discovered

4.2
### Actual behavior

This error was showing up and crashing carma whenever it happened.
### Steps to reproduce the actual behavior

1. Do this
1. Then do this...

**Comment by msmcconnell** [comment]
Resolved by above PR
