### ISSUE TITLE
UI website phase shift is not working as needed and the UI is just mock counting 15 sec

### ISSUE THREAD

**Issue by aswath1** [usdot-fhwa-stol/carma-platform#2012]
### Summary

UI website needs to be updated to account for the correct phase swift as well as proper count down over mocking 15 secs.

### Commit

isetta 

### Expected Behavior

UI website correct phase swift as well as proper count down over mocking 15 secs.

### Actual Behavior

UI website shows incorrect phase swift as well as just mocking 15 secs count down.

### Steps to Reproduce the Actual Behavior

carma start all
localhost

**Comment by MishkaMN** [comment]
Resolved by above PR
