### ISSUE TITLE
CMV and ERV Opposing direction lane index calculation edge case

### ISSUE THREAD

**Issue by MishkaMN** [usdot-fhwa-stol/carma-platform#2086]
### Summary

Previously the ERV and CMV's lane index is obtained from counting how many routable lanelets are to the right of the current lanelet. (if no right llts, then idx is 0, if there is 1, then idx is 1 etc)
This works if the CMV and ERV are both in the same direction. However, if the ERV is going opposite direction, it can also be 0 idx (because ERV is at right-most lane in its own direction), which the CMV detects erroneously as they are in a same lane if CMV is also on rightmost lane but opposite direction.

### Commit

a7039cc42f9e1a2950749a03438a1d3c0b758d04

### Expected Behavior

CMV should not detect the ERV in the opposing direction and ignore. 

### Actual Behavior

CMV detected that the ERV is on same lane and slowed down before shutting down.

### Steps to Reproduce the Actual Behavior

CMV rightmost lane
ERV rightmost lane but further ahead in distance with opposing direction.
Engage CMV and later ERV's broadcasting and observe the erroneous message on the UI that they are on a same lane

**Comment by JonSmet** [comment]
Closed by PR #2084
