### ISSUE TITLE
Destination points in ERV may include passed points

### ISSUE THREAD

**Issue by MishkaMN** [usdot-fhwa-stol/carma-platform#2088]
### Summary

During V2I integration testing of Emergency Response Use Case, it was discovered that sometimes the passed destination points can be broadcasted to the CMV despite carma-cloud's best efforts. The reason is unknown and could be due to race condition or difference in logic between determining location of the ERV. Either way, having extra guard to only route for future points (including past points in routing fails in lanelet) in the ERV would improve the stability of the plugin as not being able to route means losing track of the ERV altogether. 

### Commit

https://github.com/usdot-fhwa-stol/carma-platform/commit/a7039cc42f9e1a2950749a03438a1d3c0b758d04

### Expected Behavior

CMV is able to route given the destination points for ERV

### Actual Behavior

Currently carma-platform is not able to route if for example 6 points were given, but the location of the ERV is in the middle of the three. This would mean to "go back" to pass through the passed points, which is not possible and the logic fails.

### Steps to Reproduce the Actual Behavior

Setup V2I testing scenario.
Start CMV early.
Start ERV later on broadcasting BSMs to the infrastructure.
Notice that the points are being deducted from the BSM's part 2 message on ERV.
Yet still notice that the CMV is not able to route with given deducted points, but is only able to route once there is only 1 point left, which is always mostly far away ahead.

**Comment by JonSmet** [comment]
Closed by PR #2084
