### ISSUE TITLE
ros2 build for autoware_build_flags doesn't include cmake extensions

### ISSUE THREAD

**Issue by adev4a** [usdot-fhwa-stol/carma-platform#2114]
### Summary

The ros2 build for autoware_build_flags package doesn't include the cmake extensions defined in the package. This is required for running CUDA checks.

### Commit

Develop

### Expected Behavior

The cmake extensions defined in the package should be exported to ros2.

### Actual Behavior

The ros2 build doesn't include the extensions defined.

### Steps to Reproduce the Actual Behavior

1. Build a ros2 package dependent on autoware_build_flags, which uses one of the cmake extension commands like 'AW_CHECK_CUDA'

**Comment by MishkaMN** [comment]
resolved by above PR
