### ISSUE TITLE
Freight truck lidar time synchronization (for Silver and White trucks)

### ISSUE THREAD

**Issue by afrye51** [usdot-fhwa-stol/carma-platform#2157]
### Summary

To support UCLA’s object detection model development, the 2 Velodyne lidars (which support PPS time synchronization) on the trucks should be time synchronized. The timestamp of the data from the sensor’s clock should be used for point cloud ROS Message timestamps published by the velodyne driver.

This work should be completed for both the Silver and White trucks (Freightliners 10004 and 80550).

**Comment by JonSmet** [comment]
Closed by above PRs.
