### ISSUE TITLE
CARMA Platform ROS2 failed in simulation (XiL) environment

### ISSUE THREAD

**Issue by dan-du-car** [usdot-fhwa-stol/carma-platform#2388]
### Summary

CARMA Platform ROS2 failed and cannot engage vehicle after the simulation started. This issue depends on another issue: https://github.com/usdot-fhwa-stol/cda-telematics/issues/207

### Commit

NA

### Expected Behavior

No issue running CARMA platform ROS2 container in simulation environment.

### Actual Behavior

CARMA Platform ROS2 failed and cannot engage vehicle after the simulation started. An exception is thrown by the motion computation node - cannot store a negative time point in rclcpp::Time while in ACTIVE state.

![image](https://github.com/usdot-fhwa-stol/carma-platform/assets/51463994/6865ef0a-1b0d-47d3-8a4c-31c652e30627)

### Steps to Reproduce the Actual Behavior

Refer to setup instruction: https://usdot-carma.atlassian.net/wiki/spaces/WFD2/pages/2907996170/Development+Environment+setup+-+Telematics+tool+XiL+integration+test

**Comment by adev4a** [comment]
Closed by https://github.com/usdot-fhwa-stol/carma-utils/pull/229 and https://github.com/usdot-fhwa-stol/carma-utils/pull/230
