### ISSUE TITLE
Re-apply the fix for the Pacifica's Steering and Brake Override Issue

### ISSUE THREAD

**Issue by maefromm** [usdot-fhwa-stol/carma-platform#335]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ x] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary
The fix for the Pacifica Steering and Brake override thresholds that were done during the June Morton testing seems to have been changed back to 0.18s and 8% respectively. 

Per Caleb, calibration values will be saved if you power down the dbw module with the small round switch with the red light. If someone powered it off with the red dial switch that cuts all 12V power, the cals won't be saved. Raptor-Cal (paid NE software) is required to load the calibrations. 

Therefore created support ticket with AStuff #2177, and AStuff provided the instructions to install Raptor-Service and a license key, along with RPG with the configuration setting that we had back in June. 

Need this task to install the software and re-apply the configuration. 

### Expected behavior
Braking and Steering should not take too much effort to disengage (or release from) automation. 

### Actual behavior
Braking requires a lot of force to disengage that vehicles start to squeal during the runs. 
Steering requires a quarter or half of the turn of the wheel before it disengages, especially at higher speeds. 

### Steps to reproduce the behavior

1. Run Autoware or CARMA 3
2. Try to override using braking or steering. 

### Related work

AutonomouStuff support ticket # 2177

**Comment by maefromm** [comment]
@marchesem Could you kindly close out this ticket with the latest update, and kindly reference the document you've written for this? Thank you!

**Comment by marchesem** [comment]
-Brake override threshold was reduced from 8% to 1%

-Requirements for steering override is time based (i.e. non-zero amount of torque for x seconds). It is not based on angular position or strictly torque threshold. To increase the sensitivity of steering override, Steering_response_time was reduced from .18s to .01s

After these adjustments were made, overriding via steering and brake requires and appropriate amount of effort.
