### ISSUE TITLE
Docker does not support Kvaser CAN

### ISSUE THREAD

**Issue by msmcconnell** [usdot-fhwa-stol/carma-platform#350]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary
When trying to build docker images for the SSC the instructions for installing the AStuff Kvase can driver do not work and errors are through. 
https://autonomoustuff.atlassian.net/wiki/spaces/RW/pages/17475947/Driver+Pack+Installation+or+Upgrade+Instructions
The current workaround is to use the SocketCan configuration of the pacmod but this may not be sufficient when using radars as their is limited USB port availability on the Spectra pc. 
### Expected behavior
Kvaser can be used in docker for SSC driver and Radar drivers
### Actual behavior
Kvaser cannot be installed in docker for SSC driver
### Steps to reproduce the behavior

Try to place the commands from the above link in the docker file for the SSC interface wrapper.

**Comment by msmcconnell** [comment]
The PR's listed above this comment create a work around for this issue where SocketCAN is enabled for communicating with the Pacmod instead of Kvaser. This appears to work without issue but there are not enough USB ports to support all the radars using USB pcan adapters. Therefore, either the installation issue needs to be resolved, or the Kvaser interface card needs to be replaced with a socketcan card that can support 6 devices.

**Comment by msmcconnell** [comment]
This same issue appeared on the New Eagle repository
It was resolved by Astuff on that repo with the following installation commands
```
            apt-get install -y software-properties-common
            apt-add-repository -y ppa:jwhitleyastuff/kvaser-linux
            apt-get update -qq
            apt-get install kvaser-canlib-dev
```
NewEagleRaptor/pacifica-dbw-ros#19

This seems like the first thing we should try to resolve this.

**Comment by maefromm** [comment]
@msmcconnell Regarding your comment "but this may not be sufficient when using radars as their is limited USB port availability on the Spectra pc." : Is there an issue to track the permanent solution for this? Is this something that needs to be fixed later?

**Comment by msmcconnell** [comment]
@maefromm This is the issue to track the permanent resolution. We have a workaround by using PCAN USB adapters but I believe this issue should remain open until we can either go back to using Kvaser or demonstrate all the radars and the controller working in docker at the same time. (This is not currently possible using PCAN due to limited usb ports)

**Comment by JWhitleyAStuff** [comment]
Just a note that the PPA URL has changed to `ppa:astuff/kvaser-linux`.

**Comment by msmcconnell** [comment]
This has been resolved by the above PRs
