### ISSUE TITLE
Update Autoware fork to accommodate truck configs

### ISSUE THREAD

**Issue by TonysCousin** [usdot-fhwa-stol/carma-platform#423]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [x] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary
As part of Autoware integration into the red truck, some config changes were made.  Ben at AStuff has promised to make a branch on their Autoware 1.12 fork (in Gitlab) to store these changes.

### Expected behavior
Leidos can pull changes directly from the AStuff fork.

### Software version this applies to

Autoware 1.12

### Actual behavior
Changes need to be manually added to the FHWA repo if this update isn't put in before the next truck is ready to test.

### Related work

Link to related tickets or prior related work here.

**Comment by maefromm** [comment]
Created ASTuff support ticket 2705 to provide updates to this ticket using this Github Issue.

**Comment by TonysCousin** [comment]
Not sure if this is even relevant any more, since we have moved away from Autoware as a standalone installation.

**Comment by msmcconnell** [comment]
I can't find the exact PRs, but this has been done and the trucks have been tested successfully since the Urus release
