### ISSUE TITLE
Master Autoware repo out of date with SSC_interface

### ISSUE THREAD

**Issue by TonysCousin** [usdot-fhwa-stol/carma-platform#427]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [x] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary
The ssc_interface is a node found in the Autoware repo which communicates with the Astuff SSC. However, before the delivery of the first vehicle Astuff modified the SSC's interface and the ssc_interface node in their own Autoware fork. This change has not yet been pushed back to the main Autoware repo. They plan to do this for either the 1.13 release in Dec or the 1.14 release in 2020. Currently CARMA uses the ssc_interface provided by the Astuff repository, however it is prefered that differences between CARMA's Autoware fork and the main line Autoware fork be minimized as much as is practical. So udating the component is prefered long term.  We need to manually put the correct version into our Autoware fork until base Autoware has included it.

### Expected behavior
AStuff updates are reflected in the main Autoware.ai repo.

### Software version this applies to

Autoware 1.12

### Actual behavior
The main Autoware repo does not include the necessary AStuff updates, so they must be grabbed from the AStuff fork.

### Steps to reproduce the behavior
See above.

### Related work

Link to related tickets or prior related work here.

**Comment by saina-ramyar** [comment]
In Autoware 1.13.0 AStuff updates are added to SSC Interface.
