### ISSUE TITLE
Develop OpenDrive to LaneLet2 Converter for Geometry

### ISSUE THREAD

**Issue by itabrl** [usdot-fhwa-stol/carma-platform#431]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [x] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary
In order to use the LaneLet2 library for the world model as Autoware is in 1.13 we will need to convert our OpenDrive maps to LaneLet2's OSM format as the converter for Autoware is not yet built. This converter should be created under this task and need only cover functionality required for CARMA

### Expected behavior
Validate the produced map by autoware_lanelet2_validation node

### Software version this applies to

Develop
### Steps to reproduce the behavior

1. Do this
1. Then do this...

### Related work

Link to related tickets or prior related work here.

**Comment by msmcconnell** [comment]
Development of script began with #430 but more work is still needed

**Comment by maefromm** [comment]
As discussed, @msmcconnell @TonysCousin we are closing this issue to include the merged code for the testarossa release. @msmcconnell please create a separate issue for the MVP portion.
