### ISSUE TITLE
Develop world model for external objects (perception)

### ISSUE THREAD

**Issue by msmcconnell** [usdot-fhwa-stol/carma-platform#432]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [x] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary
To safely plan, guidance will need access to a common interface which describes static and moving objects in the world around it. This interface needs to be defined and implemented. 
### Expected behavior
Guidance has mechanism to detect and avoid collisions
### Actual behavior
Logic existed in CARMA2 but needs to be ported/re-implemented in c++ for carma3.

**Comment by maefromm** [comment]
@msmcconnell can this be closed?

**Comment by msmcconnell** [comment]
@maefromm Not yet the external objects interface has only recently been started and has a fair amount left to do.
