### ISSUE TITLE
Need Zapier fixed to create new issues in JIRA

### ISSUE THREAD

**Issue by maefromm** [usdot-fhwa-stol/carma-platform#503]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [x] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary
Zapier has stopped creating JIRA anomalies/tasks. 

Zapier account may have been tied with the former Configuration Manager and somehow that account had stopped working. Need to create a generic account for carma for Zapier and provide access to at least 3 people as backups (John, Kyle and Mae) as backups, or link it to one of the carma gmail email accounts to tie it to. 

### Expected behavior
When new issues are created in GitHub, it should create new JIRA anomalies/task/user story depending on the Issue's Label. 

Please check with @TonysCousin on the previous logic and may need to update as needed. Only documentation I found is this: 
https://usdot-carma.atlassian.net/wiki/spaces/CAR/pages/171835397/Zapier+Overview

### Software version this applies to

NA

### Actual behavior
When new Github Issue is created, no JIRA item is created. 

### Steps to reproduce the behavior
See above

### Related work

Link to related tickets or prior related work here.

**Comment by TonysCousin** [comment]
Removing anomaly checkbox, since this is a process problem, not a product problem.  In any case, it is now working with the new Zapier account in place, so closing.
