### ISSUE TITLE
Add Lanelet Connections to Vector Map

### ISSUE THREAD

**Issue by qswawrq** [usdot-fhwa-stol/carma-platform#504]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary
Using lanelet2 converter script, we can convert OpenDrive vector map to OSM format. However, the conversion does not add lanelet conversion between lanelets, such that the converted map cannot be used for routing. For example, in TFHRC vector map, we have graph: 
[routing.txt](https://github.com/usdot-fhwa-stol/CARMAPlatform/files/4074960/routing.txt)
, which can not be used to routing due to missing relations between lanelets.
### Expected behavior
Vector map can be used for routing.
### Software version this applies to

3.2.0
### Actual behavior
Converted vector map can be used for routing at current version.
### Steps to reproduce the behavior
Use lanelet2 lib to route on TFHRC vector map.
### Related work
N/A
Link to related tickets or prior related work here.

**Comment by msmcconnell** [comment]
At the moment I think this is expected as Jira task CAR-1533 has not bee completed yet.

**Comment by qswawrq** [comment]
> At the moment I think this is expected as Jira task CAR-1533 has not bee completed yet.

Then this ticket should be marked as enhancement.

**Comment by qswawrq** [comment]
Confirmed in ATEF vector map that this issue still exist.

**Comment by qswawrq** [comment]
@msmcconnell Should this be closed since CAR-1533 is merge?

**Comment by msmcconnell** [comment]
@qswawrq I believe this could be closed given that we have been able to properly route on the map now.

**Comment by qswawrq** [comment]
Implemented by #508. Closed.
