### ISSUE TITLE
Arbitrator doesn't handle SHUTDOWN state properly

### ISSUE THREAD

**Issue by msmcconnell** [usdot-fhwa-stol/carma-platform#509]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary
When the arbitrator receives, a system_alert SHUTDOWN message it will cause an error such as the following
```
terminate called after throwing an instance of 'std::invalid_argument'
platform                           |   what():  State machine attempting to process an illegal state value
```
This causes the whole node to crash with. 

This appears to be caused by the following switch statement not containing an SHUTDOWN state. While the CARMANodeHandle should handle the shutdown, it appears that it is possible this loop runs before that occurs. 
```
    void Arbitrator::run()
    {
        ROS_INFO("Aribtrator started, beginning arbitrator state machine.");
        while (!ros::isShuttingDown())
        {
            ros::spinOnce();
            switch (sm_->get_state()) 
            {
                case INITIAL:
                    ROS_INFO("Aribtrator spinning in INITIAL state.");
                    initial_state();
                    break;
                case PLANNING:
                    ROS_INFO("Aribtrator spinning in PLANNING state.");
                    planning_state();
                    break;
                case WAITING:
                    ROS_INFO("Aribtrator spinning in WAITING state.");
                    waiting_state();
                    break;
                case PAUSED:
                    ROS_INFO("Aribtrator spinning in PAUSED state.");
                    paused_state();
                    break;
                default:
                    throw std::invalid_argument("State machine attempting to process an illegal state value");
            }
        }
    }
```
### Expected behavior
I would suggest adding the SHUTDOWN state and logging a warning until the CARMANodeHandle can complete shutdown of the node. 
### Software version this applies to

CARMA System 3.2
### Actual behavior
As described in the descriptive summary
### Steps to reproduce the behavior
Run carma when the GPS/Lidar/or SSC cannot be found. This will force a system shutdown.

**Comment by TonysCousin** [comment]
Per @Supraluminal , this issue is still valid.  "the only real effect is rather than shutting down cleanly when told to the arbitrator throws an exception and shutsdown instead. Doesn’t really have a functional impact."
