### ISSUE TITLE
Load map transforms from OSM file. 

### ISSUE THREAD

**Issue by msmcconnell** [usdot-fhwa-stol/carma-platform#557]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [x] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary
To simplify usage of HD maps in carma we should load the open drive proj georeference directly from the loaded osm file and use this as the ecef to map transform
### Expected behavior
Singular source of map to ecef transforms and projections. 
### Software version this applies to

Urus release
### Actual behavior
Both the map projection and map to ECEF transform are loaded separately.

**Comment by msmcconnell** [comment]
This is effectively a duplicate issue of #360

**Comment by TonysCousin** [comment]
Closing per Mike McConnell.
