### ISSUE TITLE
Pacifica - Wiring Issues

### ISSUE THREAD

**Issue by maefromm** [usdot-fhwa-stol/carma-platform#563]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [x] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary
HW wiring concerns reported by Jeff Heger and reported to Ben/AStuff on 1/17/2020. 

See documentation for pictures. 
1. This picture shows the wire loom routed between the fuel tank and the protective shield. The protective shield does not act as a skid plate. Not pictured is the fill for the fuel tank directly above the wire loom. I suggest this should be routed above the fuel fill and not in a location that could serve as a crush point for the wires. Their current location is at the lowest point of the vehicle, closest to the ground.
2. This group of pictures shows the wiring loom under the passenger side of the vehicle. The loom makes a hard 90 degree bench, forcing the outer wheel well within an inch of the wheel. The screw holding the forward most aluminum strap has been torn out of the plastic due to the pressure of the loom being bent. I think a better system could be employed here to prevent the tire from catching the outer wheel well and prevent the looming from dangling close to the ground.

[pacifica wiring concerns.docx](https://github.com/usdot-fhwa-stol/CARMAPlatform/files/4204264/pacifica.wiring.concerns.docx)

### Expected behavior
See above. 

### Actual behavior
NA
### Steps to reproduce the behavior
NA

### Related work

Link to related tickets or prior related work here.

**Comment by msmcconnell** [comment]
This was resolved by AStuff per Jeff Heger
