### ISSUE TITLE
Convert existing Autoware Plugin into "In-lane Cruising" tactical plugin

### ISSUE THREAD

**Issue by saina-ramyar** [usdot-fhwa-stol/carma-platform#564]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [x] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary
Convert the Autoware Plugin into a tactical plugin capable of handling the In-lane Cruising CARMA feature.

### Expected behavior
NA
### Software version this applies to
CARMASystem 3.3.0
### Actual behavior
NA
### Steps to reproduce the behavior

NA

### Related work

NA

**Comment by msmcconnell** [comment]
Resolved by above PRs
