### ISSUE TITLE
Update Route to publish current lanelet ID and lanelet downtrack distance

### ISSUE THREAD

**Issue by qswawrq** [usdot-fhwa-stol/carma-platform#586]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [x] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary
Update Route to publish current lanelet ID and lanelet downtrack distance to UI to display
### Expected behavior
Current lanelet ID and lanelet downtrack distance are published in Route.msg.
### Software version this applies to

3.3.0
### Actual behavior
N/A
### Steps to reproduce the behavior
N/A
### Related work
N/A

**Comment by maefromm** [comment]
I think this can be closed as it has been implemented under PRs above.
