### ISSUE TITLE
Add MPC Follower Wrapper

### ISSUE THREAD

**Issue by saina-ramyar** [usdot-fhwa-stol/carma-platform#603]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [x] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary
The MPC Wrapper node is developed to enable CARMA to use Autoware MPC follower node.
### Expected behavior
Code builds
### Software version this applies to

3.3.0
### Related work

Link to related tickets or prior related work here.

**Comment by msmcconnell** [comment]
Resolved by above PRs
