### ISSUE TITLE
CARMA requires pre-recorded waypoints

### ISSUE THREAD

**Issue by kjrush** [usdot-fhwa-stol/carma-platform#611]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [x] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

CARMA is unable to operate without pre-driven Autoware waypoints recorded on the host vehicle.

### Expected behavior

CARMA should be able to take a user anywhere the vehicle has mapping data for and it is capable of resolving a route to that location.

### Software version this applies to

3.3.0

### Actual behavior

CARMA vehicle requires the operator run separate autoware software to record waypoints while manually driving so that it can load those waypoints later for replay.

**Comment by msmcconnell** [comment]
Resolved by vanden-plas release
