### ISSUE TITLE
Implement Truck Inspection Client to Handle Incoming Request

### ISSUE THREAD

**Issue by qswawrq** [usdot-fhwa-stol/carma-platform#613]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [x] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary
For the ACE Demo, a new system called CARMAMessenger was created with a new Truck Inspection plugin and new CARMAPlatform truck inspection plugin client. 

### Expected behavior
N/A
### Software version this applies to
N/A
### Actual behavior
N/A
### Steps to reproduce the behavior
N/A
### Related work

CAR-1778: CARMA messenger truck safety log request
CAR-1779:  Broadcast Truck safety message log
CAR-1781: CARMA messenger should receive a truck safety message log.

Link to related tickets or prior related work here.

**Comment by maefromm** [comment]
closed by the PR 614.
