### ISSUE TITLE
Name change on 3rd party ssc-interface-wrapper dependency

### ISSUE THREAD

**Issue by jtbaird** [usdot-fhwa-stol/carma-platform#648]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [x] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary
A [third party repo](https://github.com/NewEagleRaptor/raptor-dbw-ros) on which ssc-interface-wrapper is dependent has changed the names of all of its packages. It is not clear if there are any other changes that will affect functionality on the cars, and we are unable to verify due to remote work. We have [opened an issue](https://github.com/NewEagleRaptor/raptor-dbw-ros/issues/32) on the third party repo to ask for more information.
### Steps to reproduce the behavior

1. Do this
1. Then do this...

### Related work

Link to related tickets or prior related work here.

**Comment by msmcconnell** [comment]
Linked new eagle issue was resolved and no changes were made. This issue will be closed.
