### ISSUE TITLE
Fix Health Monitor for Trucks is not evaluating GPS failure only 

### ISSUE THREAD

**Issue by maefromm** [usdot-fhwa-stol/carma-platform#675]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

The Health monitor in develop is missing the logic or not evaluating the "s_1_l1_1_l2_1_g_0" which denotes GPS failure only. 

### Expected behavior
Should handle the GPS failure for trucks and unit testing should be added to check all of the combination of values. 

### Steps to reproduce the behavior
1. Make sure to implement and test health monitor unit tests. 

### Related work
https://github.com/usdot-fhwa-stol/carma-platform/pull/639 
Link to related tickets or prior related work here.

**Comment by TonysCousin** [comment]
@maefromm is it handling GPS failure in passenger cars?  What is the alert in that situation?  Should be a warning, I think.

**Comment by maefromm** [comment]
@TonysCousin alert.type = cav_msgs::SystemAlert::CAUTION; to match the car logic that Ash had implemented.

**Comment by TonysCousin** [comment]
Sounds good.  @maefromm are we ready to close this ticket?

**Comment by maefromm** [comment]
Yes fix was done on the PR above.
