### ISSUE TITLE
Sensor Fusion Node Does Not Track Radar-Detected Object Properly

### ISSUE THREAD

**Issue by qswawrq** [usdot-fhwa-stol/carma-platform#68]
### Descriptive summary
SensorFusion node is responsible for assigning object IDs to any objects detected by radar. The ID should be unique and consistent to the same object. However, this functionality fails to function normally.
### Expected behavior
If there is one vehicle in front of the host vehicle, the sensor fusion should assign a unique and consistent ID to it to indicate that is the same vehicle.
### Actual behavior
The ID assigned to the same object keeps changing every few seconds.
### Steps to reproduce the behavior
Echo the tracked object topic from sensor fusion while a vehicle is sitting in front of the host vehicle. Observe the ID associated with that vehicle.
### Related work
N/A

**Comment by qswawrq** [comment]
Tried to adjust some fusion parameters with no success. It indicates we should evaluate the actual logic in the SF code for determining whether two objects from two time step is the same one is valid.

**Comment by SAMBUFER** [comment]
Вперед

**Comment by TonysCousin** [comment]
This applies to the Carma2 architecture only, so is now OBE.
