### ISSUE TITLE
CARMA Platform - Truck Inspection Plugin Client - Update

### ISSUE THREAD

**Issue by dan-du-car** [usdot-fhwa-stol/carma-platform#688]
### Types of Issue

Fix: Carma messenger requirements change
- [ ] Anomaly report (something appears to not work correctly)
- [x] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary
Additional changes mentioned during sprint review: 

- On the safety log details page, the “ADS Health Status”  logic will need to be updated to signify faults in the ADS system. 
- On the safety log details page,  a new field shall be added to determine if the truck’s automation status. 

Additional changes requested via email:
- On the safety log request page, add the license plate and state of issue, in addition to VIN that currently exists.
- Acceptance Critieria: 
- Meet internally to finalize the new logic for all changes described above. 
- Develop the changes to support all the requests above.
- Update the “ADS Health Status” logic on the CARMAPlatform Truck Inspection Plugin Client.
- Add the new “ADS Automation Status” to the CARMAPlatform Truck Inspection Plugin Client. 
- Add the state and license to the necessary topics to support the changes above. 
- Then “ADS Health Status” listen to the /System_alert topic published from CARMAPlatform by Health_monitor node
- “ADS Health Status“ shows SHUTDOWN -black color when the Auto status goes to “Not Engaged“
- “ADS Health Status“ initially shows NOT READY - gray color when the Auto status goes to “Engaged“.  then  Show the latest alert type below:

CAUTION  - yellow 
WARNING - orange
NOT READY - grey
DRIVER_Ready - green
SHUTDOWN-black
FATAL- red
alert type reference:  
Code Peer Reviewed.
Locally integration tested.

Update the Design Documentation. Peer review can be done outside of this sprint. 

### Software version this applies to

develop

### Steps to reproduce the behavior

1. Do this
1. Then do this...

### Related work

Link to related tickets or prior related work here.
https://usdot-carma.atlassian.net/browse/CAR-2350

**Comment by maefromm** [comment]
Truck Inspection Client doesn't need any kind of reset logic for that indicator (ads_health_Status) when guidance/state (ads_auto_status) is "Not Engaged"
