### ISSUE TITLE
Autoware Cannot build due to query merge

### ISSUE THREAD

**Issue by MishkaMN** [usdot-fhwa-stol/carma-platform#699]
### Types of Issue

- [X] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary
Autoware is failing to build because query.tpp, a new file added in the recent merge, is not referenced in the CMakeLists.txt. This file should be correctly referenced among the header files. 

### Expected behavior
Autoware should build without a failure.

### Software version this applies to

On carma-develop branch of autoware.ai soon after 3.3.0 

### Actual behavior
Failing to build in Circle CI

### Steps to reproduce the behavior

Run CircleCI to build
or locally build autoware.ai 

### Related work

Link to related tickets or prior related work here.

**Comment by msmcconnell** [comment]
Resolved by linked PR.
