### ISSUE TITLE
docker-compose support for CUDA

### ISSUE THREAD

**Issue by itabrl** [usdot-fhwa-stol/carma-platform#701]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [`x`] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary
cukrrecnt docker images support CUDA, In order to run CARMA CUDA support needs be included for docker-compose. The goal is to identify the changes required for carma-config and add a CUDA support to it. Does not need to be shown as compatible with the Autoware build.

### Related work

Link to related tickets or prior related work here.
https://usdot-carma.atlassian.net/browse/CAR-2316

**Comment by msmcconnell** [comment]
Closing as resolved by https://github.com/usdot-fhwa-stol/carma-config/pull/63
