### ISSUE TITLE
Request for logic to remove RegulatoryElements from a Lanelet map

### ISSUE THREAD

**Issue by MishkaMN** [usdot-fhwa-stol/carma-platform#705]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [X] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

In order to update a lanelet2 map to support geofences we will need to be able to remove regulatory elements from a lanelet map so they can be replaced. This request is to develop a function in autoware.ai/lanelet2 that can remove regulatory elements from the map. This should be done in such a way that the resulting map is self valid though it is acceptable if it cannot be routed over when a regulation required be CARMAUsTrafficRules is removed as it is expected that we will add this back in right after updating a regulation. 

### Expected behavior

A call to this function should remove all references to that regulatory element in the map

### Software version this applies to

On carma-develop branch of autoware.ai soon after 3.3.0

### Actual behavior
N/A
### Steps to reproduce the behavior
N/A
### Related work

Link to related tickets or prior related work here.

**Comment by msmcconnell** [comment]
Resolved by above PR
