### ISSUE TITLE
Development build scripts - update to support usdotstoldev and develop image

### ISSUE THREAD

**Issue by maefromm** [usdot-fhwa-stol/carma-platform#708]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary
1)
The carma config script does not support usdotstoldev. When you call carma config remote list, install, and others, it points to usdotfhwastol/master. Need to have a –d option as well like build-image.sh to point to usdotstoldev.

 https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/engineering_tools/carma

2) in addition, the carma-platform build-sh needs to be updated to support development configs already pointing to usdotstoldev and develop image. 

Getting the error below: 
![image](https://user-images.githubusercontent.com/27976519/83141272-60b59f00-a0bd-11ea-9795-20a396a5007f.png)

### Expected behavior
Should support the development builds and configuration without errors. 

### Software version this applies to

develop

### Actual behavior
explained above. 

### Steps to reproduce the behavior
Run through all the carma config options like remote list, install, set, start, etc. 
Install carma-config develop image, set and install. 

### Related work

Link to related tickets or prior related work here.

**Comment by msmcconnell** [comment]
Resolved by above PRs
