### ISSUE TITLE
Lightbar is not accessible by carma on silver lexus

### ISSUE THREAD

**Issue by msmcconnell** [usdot-fhwa-stol/carma-platform#716]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary
Trying to start the lightbar driver using carma on the silver results in the following error

```
lightbar-driver    | *   Trying 192.168.88.28...
lightbar-driver    | * connect to 192.168.88.28 port 80 failed: No route to host
lightbar-driver    | * Failed to connect to 192.168.88.28 port 80: No route to host
```

Attempting to start manually from the PDS also failed and the target IP from the vehicle PC could not be reached.
### Expected behavior
Lightbar can be controlled with ROS interface and or started manually.
### Software version this applies to

develop after 3.3.0 and 3.3.0 itself
### Actual behavior
See description
### Steps to reproduce the behavior
Carma start all
### Related work

Link to related tickets or prior related work here.

**Comment by MishkaMN** [comment]
Reprogrammed the lightbar as the wiring was a little different than other cars. Uploaded the custom config file on vector as well as the documentation on how to troubleshoot the config.
