### ISSUE TITLE
removeRegulatoryElements function not completely removing elements

### ISSUE THREAD

**Issue by MishkaMN** [usdot-fhwa-stol/carma-platform#719]
### Types of Issue

- [X] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary
Recently added removeRegulatoryElements function in autoware/common/lanelet2_extension/utils/utilities.h is not accounting for the fact that lanelet and area layers themselves have another indexes that still indicate that the elements are in the map although those elements are not. This is different than lanelet and area elements themselves having indexes inside to record those elements, which is previously thought to handle this overlooked scenario. The tests did not cover correctly because the findReference uses different type of querying method to check that relation, and it was correctly removed according to that.

The function will be used by geofence operations in the future and as geofence affects regulatory elements, this could erroneously impact routes. While there is not any logic that uses this function yet, it will break the upcoming geofence operations and would not make intended routing possible, so this case still should be resolved urgently.

### Expected behavior
The function should remove indexes the relationship between regulatory elements and primitivesin lanelet and area layers.

### Software version this applies to

On carma-develop branch of autoware.ai soon after 3.3.0
### Actual behavior
See above.
### Steps to reproduce the behavior

```
//pass in the regem list that one wants to remove from the map
lanelet::utils::removeRegulatoryElements({regem}, sample_map_ptr);
ASSERT_EQ(sample_map_ptr->laneletLayer.findUsages(regem).size(), 0);
// it will still show that some lanelet has that regem although it is removed.
```

### Related work

Link to related tickets or prior related work here.

**Comment by msmcconnell** [comment]
Resolved by above PR
