### ISSUE TITLE
Request for logic to update the carma_wm_ctrl copy of the map with geofence speed limit changes

### ISSUE THREAD

**Issue by MishkaMN** [usdot-fhwa-stol/carma-platform#722]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [X] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary
This request is to develop a logic to update the carma_wm_ctrl local map copy to support updates to speed limit regulatory elements from geofences. This is the first of its features in line where geofence requests to make changes to the map and carma should be able to accommodate that.

For now it is acceptable to assume all speed limit changes will be at a lanelet boundary. Once the local map is updated it does not need to be published, that is handled in a future story. Integration testing should focus on the carma_wm_ctrl node remaining operational when sent a speed limit geofence. 

### Expected behavior
Sending control message (geofence) requests to the topic the carma_wm_ctrl listens to updates the map with new speed limit changes.

### Software version this applies to

N/A
### Actual behavior
N/A
### Steps to reproduce the behavior
N/A

### Related work

Link to related tickets or prior related work here.

**Comment by msmcconnell** [comment]
Resolved by above PRs
