### ISSUE TITLE
Tactical plugin for platooning

### ISSUE THREAD

**Issue by itabrl** [usdot-fhwa-stol/carma-platform#731]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [`x`] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary
Platooning Tactical plugin based on detail design to work as a service and provide trajectory for strategic plugin.

### Related work

Link to related tickets or prior related work here.

**Comment by msmcconnell** [comment]
Resolved by above PRs
