### ISSUE TITLE
Sonar functionality needed to ignore issues in blocks

### ISSUE THREAD

**Issue by jtbaird** [usdot-fhwa-stol/carma-platform#732]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [x] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary
In order to more accurately analyze carma code, we need the ability to have sonar selectively ignore certain blocks of code.

### Expected behavior
Developers should be able to wrap blocks of code in tags which cause sonar to not scan the code within the tags.

### Software version this applies to

Current.
### Actual behavior
Sonar ignores the tags we have configured.

### Steps to reproduce the behavior

1. use the SONAR_STOP and SONAR_START tags at the beginning / end of a block of code
2. run a scan
3. see on the scan results that the block between the tags was still analyzed

### Related work
#729 
Link to related tickets or prior related work here.

**Comment by msmcconnell** [comment]
Resolved by above PRs
