### ISSUE TITLE
Basic collision checking for CARMA

### ISSUE THREAD

**Issue by itabrl** [usdot-fhwa-stol/carma-platform#734]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [x] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary
Basic collision checking for CARMA based on Motion detection implemented in CARMAUtiles.

**Comment by msmcconnell** [comment]
Resolved by above PR
