### ISSUE TITLE
Platooning Strategic Plugin

### ISSUE THREAD

**Issue by saina-ramyar** [usdot-fhwa-stol/carma-platform#738]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [x] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

Strategic plugin in charge planning platooning maneuver and platoon state machine.

### Expected behavior
The node should request maneuver plan, communicate with other vehicles, and keep track of the vehicle's role in the platoon.

### Software version this applies to
3.3.0

### Related work

Link to related tickets or prior related work here.

**Comment by msmcconnell** [comment]
Resolved by above PR
