### ISSUE TITLE
Add Platoon Control Plugin

### ISSUE THREAD

**Issue by saina-ramyar** [usdot-fhwa-stol/carma-platform#750]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [x] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary
Platooning control plugin is responsible for maintaining the inter-vehicle gap and driving within lane boundaries.

### Expected behavior
Platoon spacing is stable and vehicle drives inside the lane.

### Software version this applies to

3.3.0
### Steps to reproduce the behavior

1. Do this
1. Then do this...

### Related work

Link to related tickets or prior related work here.

**Comment by msmcconnell** [comment]
Resolved by above PR
