### ISSUE TITLE
Guidance "get_registered_plugins" and "get_active_plugins" does not show the required plugins

### ISSUE THREAD

**Issue by maefromm** [usdot-fhwa-stol/carma-platform#761]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary
During the UI implementation for Basic Travel using the integration/routing branch of carma-platform, we found that the following topics displayed the wrong list of plugins: 

/guidance/plugins/get_registered_plugins 
/guidance/plugins/get_active_plugins 

### Expected behavior
Should show at least 1 plugin for Strategic, Tactical and Control plugin types. Except for Platooning, Lane Change and maybe Yield was expecting as shown on the attachment below. 
![image (12)](https://user-images.githubusercontent.com/27976519/88218516-289a8a80-cc2e-11ea-8eaf-1ec7706af5ff.png)

### Software version this applies to

INTEGRATION/ROUTING branch after v3.3.0

### Actual behavior
See attached. 
![image (11)](https://user-images.githubusercontent.com/27976519/88218341-e8d3a300-cc2d-11ea-92bf-0aaefde5cf1e.png)

### Steps to reproduce the behavior
1. Build integration/routing branch of carma-msgs and carma-platform. 
2. run carma start all. 
3. echo the topics above. 

### Related work
Link to related tickets or prior related work here.
https://usdot-carma.atlassian.net/browse/CAR-2512

**Comment by maefromm** [comment]
Per @kjrush the Autoware Plugin should be updated to type = Tactical and the name = In-Lane Cruising
![image (13)](https://user-images.githubusercontent.com/27976519/88218711-6ac3cc00-cc2e-11ea-8d48-37d4357e207a.png)

As for Route Following and Pure Pursuit plugins, need further research. 

@dan-du-car needs these topics to display and not able to fake the data since it is a service call.

**Comment by TonysCousin** [comment]
Marking sev 1 since it appears that plugins cannot be reliably selected.

**Comment by TonysCousin** [comment]
Discussion w/Mae, Kyle, Mike resolve that this is sev 3 because the effect is that the plugin list won't display, and individual plugins won't be able to be deactivated (via UI), but we expect that the UI will otherwise work and allow the vehicle to drive.
