### ISSUE TITLE
CARMA requires ControlRequest logic to be implemented in carma_wm_ctrl

### ISSUE THREAD

**Issue by lewisid** [usdot-fhwa-stol/carma-platform#770]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [x] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary
CARMA requires logic to allow the vehicle to request traffic rules from CARMA Cloud based on the route using a ControlRequest message that is populated with route information once it has been received.
### Expected behavior
CARMA should be able to receive route information from CARMA Cloud and use it to populate a ControlRequest message containing 
### Software version this applies to

3.3.0
### Actual behavior
CARMA requires the user to manually publish a value to the `route_lanelet_ids_array` on the `/route` topic in order to acquire the information necessary to populate the ControlRequest message. 
### Steps to reproduce the behavior

N/A

### Related work

N/A

**Comment by msmcconnell** [comment]
Resolved by above PR
