### ISSUE TITLE
Update message node to account for Geofence Request Message

### ISSUE THREAD

**Issue by saina-ramyar** [usdot-fhwa-stol/carma-platform#773]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [x] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary
The Geofence request message definition is changed, so the message node should be updated to account for the changes.
### Software version this applies to

CARMA Platform 3.3.0
CARMA Messenger

### Steps to reproduce the behavior

1. Do this
1. Then do this...

### Related work

Link to related tickets or prior related work here.
#748

**Comment by MishkaMN** [comment]
Merged with above PR https://github.com/usdot-fhwa-stol/carma-messenger/pull/31
