### ISSUE TITLE
CARMA Web UI - Redesign for Basic Travel Use Case

### ISSUE THREAD

**Issue by dan-du-car** [usdot-fhwa-stol/carma-platform#776]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [x] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary
This issue will cover all the related changes to the UI redesign of the layout and cover any changes related to the Basic Travel Use Case. This covers multiple stories in JIRA as mentioned below. 

https://usdot-carma.atlassian.net/browse/CAR-2512
https://usdot-carma.atlassian.net/browse/CAR-3031
https://usdot-carma.atlassian.net/browse/CAR-3032

### Expected behavior
See description above. 

### Software version this applies to

Using integration/routing branch, created a new integration/ui branch to capture the new updates for UI and manage in separate branch until Wanderer is released. 

### Actual behavior
NA

### Steps to reproduce the behavior
New implementation. 

### Related work
Link to related tickets or prior related work here.
See above links.

**Comment by maefromm** [comment]
Reported the https://github.com/usdot-fhwa-stol/carma-platform/issues/761 closed that was found under this.

**Comment by dan-du-car** [comment]
New PR is created : https://github.com/usdot-fhwa-stol/carma-web-ui/pull/47

**Comment by dan-du-car** [comment]
https://github.com/usdot-fhwa-stol/carma-web-ui/pull/47

**Comment by dan-du-car** [comment]
https://github.com/usdot-fhwa-stol/carma-web-ui/pull/47

**Comment by msmcconnell** [comment]
Resolved by above PRs
