### ISSUE TITLE
White Cadillac Issue - Vehicle Bus Timeout and DSRC Driver Disconnected

### ISSUE THREAD

**Issue by maefromm** [usdot-fhwa-stol/carma-platform#79]
**Descriptive summary**
On 11/30/2018, after deployment of "Carma Platform 2.8.1.5467-develop289", received a Vehicle Bus Timeout and DSRC Driver Disconnected message when manually starting the platform via command line. 
![snapshot](https://user-images.githubusercontent.com/27976519/49316850-50b90100-f4c0-11e8-93f0-db698cc8032c.JPG)

**Expected behavior**
CARMA Platform should start with no such errors. 

**Actual behavior**
Cannot start the platform due to this errors on White Vehicle. 

 **Steps to reproduce the behavior**
1. Either start the platform via GUI interface and check the logs, or do it via command line. 

 **Related work**
N/A

**Link to related tickets or prior related work here.**
N/A

**Log Files**
[20181130-154354_White.zip](https://github.com/usdot-fhwa-stol/CARMAPlatform/files/2635083/20181130-154354_White.zip)

**Comment by TonysCousin** [comment]
This applies to the Carma2 architecture only, so is now OBE.
