### ISSUE TITLE
Novatel GPS driver not connecting on Silver lexus

### ISSUE THREAD

**Issue by msmcconnell** [usdot-fhwa-stol/carma-platform#793]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary
When running carma on the silver lexus the novatel driver cannot connect to the hardware and throws the following error. 
```
novatel-gnss-imu-driver    | [ERROR] [1596215887.692769283]: Unable to connect: connect: Connection refused
novatel-gnss-imu-driver    | [ERROR] [1596215887.692792250]: Error connecting to device <tcp:192.168.74.10:2000>: connect: Connection refused
```
What is strange is that the novatel can still be reached at the target IP so the source of the error is not immediately obvious. 
### Expected behavior
All hardware drivers can connect without errors
### Software version this applies to

develop after 3.3.0
### Actual behavior
See above error
### Steps to reproduce the behavior
Install develop build on silver lexus and run carma start all

### Related work

Link to related tickets or prior related work here.

**Comment by MishkaMN** [comment]
Found that novatel was reset. It was using its default port 3001 and IMU was no longer configured showing INS_INACTIVE.
Resolved it by using Novatel Connect, reuploaded the configuration commands in vector for silver lexus.
Verified that the GPS and INS (IMU) were giving meaningful data (not 0 entries), by looking at novatel interface in the browser and orientation of /localization/gnss_pose in rviz (X (red) should be forward Y (green) should be left)
