### ISSUE TITLE
Green Cadillac Issue - Pinpoint Driver FAULT

### ISSUE THREAD

**Issue by maefromm** [usdot-fhwa-stol/carma-platform#80]
**Descriptive summary**
On 11/30/2018, after deployment of "Carma Platform 2.8.1.5467-develop289", received a Pinpoint Driver Fault based on the Interface Manager logs see logs below. 

**Expected behavior**
CARMA Platform should start with no such errors. 

**Actual behavior**
Cannot start the platform due to this errors on Green Vehicle. 

 **Steps to reproduce the behavior**
1. Either start the platform via GUI interface and check the logs, or do it via command line. 

 **Related work**
N/A

**Link to related tickets or prior related work here.**
N/A

**Log Files**
[20181130-160704_Green.zip](https://github.com/usdot-fhwa-stol/CARMAPlatform/files/2635098/20181130-160704_Green.zip)

**Comment by TonysCousin** [comment]
This applies to the Carma2 architecture only, so is now OBE.
