### ISSUE TITLE
Add localization status report

### ISSUE THREAD

**Issue by msmcconnell** [usdot-fhwa-stol/carma-platform#800]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [x] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary
To allow the user and other system components to better understand the status of localization, a report should be generated at the localization frequency 10Hz and provides a simple description of status that can be used by the UI to report to the user.

### Expected behavior
Localization status reported using single message and topic that can be used by the UI

### Software version this applies to

develop after 3.3.0
### Actual behavior
No unified status reporting exists. 
### Steps to reproduce the behavior
N/A

### Related work
Jira issue CAR-3109
Link to related tickets or prior related work here.

**Comment by MishkaMN** [comment]
Resolved with above PRs
