### ISSUE TITLE
Intermittent ROS Connection Closed 

### ISSUE THREAD

**Issue by maefromm** [usdot-fhwa-stol/carma-platform#81]
**Descriptive summary**
On 11/30/2018, discussed with Mike and Kyle the potential reason for this issue. Kyle suggested it is most likely it is the socket connection still pending when the main page loads, and therefore suggested to have UI re-try to connect to the websocket multiple times similar to system ready status. 

**Expected behavior**
CARMA Platform should start with no such errors. 

**Actual behavior**
Cannot start the platform due to this errors and intermittently appears on every other vehicle. 

 **Steps to reproduce the behavior**
1. It's intermittent, so trial and error to reproduce this error. 

 **Related work**
N/A

**Link to related tickets or prior related work here.**
N/A

**Comment by TonysCousin** [comment]
Closing as this has not been a problem for many months. Not clear if it is related to Carma2 architecture.
