### ISSUE TITLE
Develop branch: extraneous include statements prevent software build

### ISSUE THREAD

**Issue by dan-du-car** [usdot-fhwa-stol/carma-platform#821]
### Types of Issue

Carma build  issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary
extraneous include statements prevent software build

### Software version this applies to

Develop after 3.3.0.
### Steps to reproduce the behavior

Removed below includes from : (https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/motion_computation/include/motion_computation_worker.h
and https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/motion_computation/src/motion_computation_worker.cpp)
#include <autoware_msgs/DetectedObject.h>
#include <autoware_msgs/DetectedObjectArray.h>

`
```
 mkdir -p ~/catkin_ws/src
 cd ~/catkin_ws
 git clone https://github.com/usdot-fhwa-stol/autoware.ai 
cd src
 git clone https://github.com/usdot-fhwa-stol/carma-msgs 
 git clone https://github.com/usdot-fhwa-stol/novatel_gps_driver
git clone https://github.com/usdot-fhwa-stol/carma-platform
git clone https://github.com/usdot-fhwa-stol/carma-utils
 cd ~/catkin_ws/src/carma-patform
./carma_build.bash -a ../../autoware.ai/
```
`

### Expected behavior
Built in source code without issue.  ~/catkin_ws/build, install, devel folders are generated

### Related work

Link to related tickets or prior related work here.

**Comment by msmcconnell** [comment]
Resolved by above PR
