### ISSUE TITLE
Implement "Autoware Plugin"/"In-lane Cruising" Plugin to use CARMA external objects interface

### ISSUE THREAD

**Issue by itabrl** [usdot-fhwa-stol/carma-platform#827]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [x] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary
Implement "Autoware Plugin"/"In-lane Cruising" Plugin to use CARMA external objects interface based on new detail desing to include object handling.

### Software version this applies to

develop after 3.3.0

### Related work

Link to related tickets or prior related work here.

**Comment by msmcconnell** [comment]
Resolved by https://github.com/usdot-fhwa-stol/carma-platform/pull/1104
