### ISSUE TITLE
Autoware Plugin not generating trajectory

### ISSUE THREAD

**Issue by saina-ramyar** [usdot-fhwa-stol/carma-platform#834]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary
During integration test it was noticed that the autoware plugin with external object interface does not generate trajectories and therefore the vehicle is not moving.
### Expected behavior
The autoware plugin should generate valid trajectories.
### Software version this applies to

3.3.0
### Actual behavior
During integration test it was noticed that the autoware plugin with external object interface does not generate trajectories and therefore the vehicle is not moving.
The autoware plugin without object avoidance logic is able to generate trajectories.
### Steps to reproduce the behavior

1. Build carma when autoware has object avoidance logic 
2. carma start all and localize and select route
3. Notice that topic /guidance/plan_trajectory is empty and vehicle does not move.

### Related work
#827 
Link to related tickets or prior related work here.

**Comment by msmcconnell** [comment]
@TonysCousin You can probably downgrade this issue, now that the culprit PR has been reverted.

**Comment by TonysCousin** [comment]
Changing to sev 2 since a workaround has been put into place, but the workaround removes desirable functionality, so this still needs to be resolved fairly soon.

**Comment by msmcconnell** [comment]
Resolved by above PR
