### ISSUE TITLE
CARMA requires logic to report current geofences to UI

### ISSUE THREAD

**Issue by lewisid** [usdot-fhwa-stol/carma-platform#845]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [x] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary
As identified in CAR-2785: Create High Level Design for Basic TravelDONE, UI needs a topic to report whether or not the vehicle is currently in a geofence and if it is what traffic rule is applied. Initially the only rule to check is the speed advisory. 

Logic will need to be added to carma_wm_ctrl to check the current vehicle position against the geofences and report if the vehicle is in a geofence and if so what new rules (speed limit) are being applied there. 

### Expected behavior
CARMA will be able to compare the vehicle's current position and determine whether or not it matches the coordinates of an active geofence. A message will then be published describing whether or not the vehicle is in an active geofence and the distance to the nearest active geofence.
### Software version this applies to

3.3.0
### Actual behavior
CARMA compares the coordinates of the vehicle's current position to those of the active geofences (a set of ids are used to store a list of active geofences and their information). Once a message containing the vehicle's current position is published, a separate message is published on the /message/active_geofence topic displaying whether or not the vehicle is on an active geofence as well as an enumerated value corresponding to the geofence type. Currently, the only geofence type available is the speed limit.

### Related work

Link to related tickets or prior related work here.

**Comment by MishkaMN** [comment]
resolved by above PRs
