### ISSUE TITLE
 CARMA Platform stand alone calibration

### ISSUE THREAD

**Issue by aswath1** [usdot-fhwa-stol/carma-platform#850]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [x] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary
Since we are now in a position that Carma would live on its own on a vehicle (does not need a separate Autoware installation beside it), we need to be able to do everything needed on a vehicle with just the tools provided by Carma. In particular, the white Pacifica will not have Autoware installed when delivered, and our third party stakeholders cannot be counted upon to have Autoware installed. Carma needs to stand alone.

Carma installation will need to fully support vehicle assembly assessment and calibration of the sensors at any time.
### Steps to reproduce the behavior

1. Do this
1. Then do this...

### Related work

Link to related tickets or prior related work here.

**Comment by msmcconnell** [comment]
This was resolved by above PRs
