### ISSUE TITLE
CARMA does not have an upper limit on output speed

### ISSUE THREAD

**Issue by kjrush** [usdot-fhwa-stol/carma-platform#856]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [x] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

Unlike CARMA 2, CARMA3 does not yet have an upper limiter with both configurable and hard-coded upper bounds on speed outputs to the controller. This may allow for unsafe operation of the vehicle in the event that there are software errors or other malfunctions that command large speeds.

### Carma version where this issue was discovered
3.3.0
### Expected behavior
CARMA should not output speeds higher than the lower of a configurable limit (via parameters) or a hard-coded upper limit of 80mph.

### Actual behavior
CARMA3 has no such limit.

**Comment by MishkaMN** [comment]
Resolved by https://github.com/usdot-fhwa-stol/autoware.ai/pull/118 PR
