### ISSUE TITLE
Motion computation node cannot be found by carma

### ISSUE THREAD

**Issue by MishkaMN** [usdot-fhwa-stol/carma-platform#861]
### Types of Issue

- [X] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

When carma is from develop and run by carma start all, motion_computation node cannot be found. See following error picture.
![image](https://user-images.githubusercontent.com/20613282/93357431-4a6b5480-f80e-11ea-8c53-1b545dc59660.png)
Although not exactly sure, the issue seem to be just launch config file error.
**This only affects prediction of external object motion, but vehicle operations are still possible.**

### Carma version where this issue was discovered

carma-platform develop 3.3.0+
### Expected behavior
motion_computation node should not crash
### Actual behavior

it crashed when carma is launched
### Steps to reproduce the actual behavior

clone fresh develop branch from carma-platform
set the development carma-config
run carma start all

**Comment by msmcconnell** [comment]
Resolved by above PR
