### ISSUE TITLE
Lidar/Lidar calibration in Silver truck is off

### ISSUE THREAD

**Issue by msmcconnell** [usdot-fhwa-stol/carma-platform#862]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

While running CARMA Platform in the silver truck it was observed that the lidar scans are clearly not aligned as features we showing up as duplicated. 

### Carma version where this issue was discovered

CARMA Platform develop after 3.3.0
### Expected behavior
Both lidar scans should overlap so they appear as a unified view of the world.
### Actual behavior

Lidar scans clearly show duplicated features
![image](https://user-images.githubusercontent.com/10292079/93601986-97266b00-f987-11ea-8459-f541736356f9.png)

### Steps to reproduce the actual behavior
carma start all
Launch rviz
localize
Look at scans in rviz

**Comment by TonysCousin** [comment]
Marking sev 2 as it prevents localization (a critical function), but the workaround is to use another truck.

**Comment by TonysCousin** [comment]
Cam Brown of AStuff recalibrated it on 9/30/20.

**Comment by TonysCousin** [comment]
Closing now that the PR is merged.
