### ISSUE TITLE
Remove java version message node launch from message.launch and carma-messenger launch file and verify cpp message node working for MobilityOperation msg

### ISSUE THREAD

**Issue by dan-du-car** [usdot-fhwa-stol/carma-platform#864]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

Java message node is deprecated and need to be removed from the message.launch file
Verify that cpp_message_node is running and working after updating the message.launch
### Carma version where this issue was discovered
CARMA 3.3.0

### Expected behavior
All the topics advertised/subscribed by the cpp_message_node should be found with rostopic list.
Verify that MobilityOperation message are parsed and published to outbound_binary_msg
Verify that cpp_message_node  can receives and parses data(MobilityOperation type) properly by subscribing to /inbound_binary_msg and publishes data to appropriate topics.
### Actual behavior

No data(MobilityOperation type) is published to outbound_binary_msg
No data(MobilityOperation type) is published to inbound_binary_msg 
### Steps to reproduce the actual behavior

build carma platform into docker image
build carma config into docker image
carma start all 
publish data to /mobility_operation_outbound advertised in truck_inspection_client node
verify the mobility_operation_outbound is remap to outgoing_plain_mobility_operation_message subscribed in cpp_message node
rostopic echo listen to  outbound_binary_msg in cpp_message node
### Related work

https://github.com/usdot-fhwa-stol/carma-messenger/pull/30

**Comment by msmcconnell** [comment]
Java message node is not yet deprecated as BSM/Map/SPaT all still require it. However, it is worth investigating if the message node and cpp_message node are truly interoperable.

**Comment by TonysCousin** [comment]
Marking sev 1 since it seems that no communications are possible at this time, and Carma is all about communicating.
