### ISSUE TITLE
Integration/ui branch - CARMA Web UI integration testing bug fix

### ISSUE THREAD

**Issue by dan-du-car** [usdot-fhwa-stol/carma-platform#869]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

Fix any issues during the integration testing in car silver lexus 
### Carma version where this issue was discovered

CARMA 3.3.0
### Expected behavior
Login/Logout from UI can also kill/launch backend carma-platform process
Select a route
Engage guidance
Update widget topics subscription, and widgets should display information that best serve the current vehicle status 
### Actual behavior

Some errors showed in the developer tool console
Some widgets in display area do not display the message, or the widgets subscribe to incorrect topics.

### Steps to reproduce the actual behavior

Pull the latest code from integration routing branch from repos: carma-platform, carma-msgs, carma-config, carma-web-ui (integration/ui branch instead), and pull other drivers from dockerhub.
Run carma-platform, carma related drivers, carma-config, and carma-web-ui.

**Comment by msmcconnell** [comment]
Resolved by above PRs
