### ISSUE TITLE
Silver Lexus: left camera holder broken

### ISSUE THREAD

**Issue by MishkaMN** [usdot-fhwa-stol/carma-platform#870]
### Types of Issue

- [X] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

When I was integration testing in the silver lexus, I accidentally broke the clipper that holds the left camera while trying to raise the monitor higher. The camera itself is fine, and CARMA is operational without it. Currently it can sit by itself on the clipper although it is broken, but a sudden jerk will make it fall off. Either it needs to be glued back or replace the holder. And the camera may need to be calibrated again.
![Image from iOS](https://user-images.githubusercontent.com/20613282/94161667-ef5fe000-fe53-11ea-98a4-9d9c2df29752.jpg)

### Carma version where this issue was discovered

not a software issue, but CARMA 3.3.0+
### Expected behavior
Left camera is placed back firmly and recalibrated on Silver Lexus.

### Actual behavior

The camera can fall off while driving. 

### Steps to reproduce the actual behavior

See above.

**Comment by maefromm** [comment]
Opened AStuff ticket. "Your request (3431) has been received and is being reviewed by our support staff."

**Comment by MishkaMN** [comment]
This particular issue was resolved.
