### ISSUE TITLE
White Pacifica - Spectra Monitors are not mounted

### ISSUE THREAD

**Issue by maefromm** [usdot-fhwa-stol/carma-platform#891]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [x] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

During acceptance testing of the White Paciica, the spectra monitors were not mounted. There are no mounting hardware available currently. 

### Carma version where this issue was discovered

NA

### Expected behavior
Monitors are mounted

### Actual behavior

NA

### Steps to reproduce the actual behavior

NA

**Comment by msmcconnell** [comment]
Monitors are mounted and working.
