### ISSUE TITLE
White Pacifica - Configure NAS 

### ISSUE THREAD

**Issue by maefromm** [usdot-fhwa-stol/carma-platform#893]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [x] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

During acceptance, 10/2/20, the NAS is working by default however the IP configuraiton on Windows side needs to be addressed by Leidos. Cannot ping at this time which means we need the IP configuration set. 

### Carma version where this issue was discovered

NA

### Expected behavior
See above. 

### Actual behavior

See above

### Steps to reproduce the actual behavior

NA

**Comment by msmcconnell** [comment]
NAS has been working in the white pacifica for some time now. Will close
