### ISSUE TITLE
White Pacifica - Install NVidia Stack and CUDA

### ISSUE THREAD

**Issue by maefromm** [usdot-fhwa-stol/carma-platform#894]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [x] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

During Acceptance Testing, found that the NVIDIA stack and CUDA needs to be installed to perform calibrations with lidar and camera and object detection. 

### Carma version where this issue was discovered

develop after 3.3.0

### Expected behavior
With this enhancement, be able to perform the camera and lidar calibrations and object detection using Carma software alone. Previously, we had been relying on an installation of Autoware to support these activities.

### Actual behavior

See above.

**Comment by msmcconnell** [comment]
Resolved by this PR https://github.com/usdot-fhwa-stol/autoware.ai/pull/135
