### ISSUE TITLE
Fix unit test failures on develop

### ISSUE THREAD

**Issue by lewisid** [usdot-fhwa-stol/carma-platform#902]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

Two of the test cases from WMTestLibForGuidanceTest.cpp had failed after the feature/validate_speed_limits branch had been merged into develop.
### Carma version where this issue was discovered

3.3.0
### Expected behavior
Each of the unit tests for carma_wm pass with all conditions met.
### Actual behavior

Two of the test cases in carma_wm fail: setSpeedLimitTest() and getGuidanceTestMap() in WMTestLibForGuidanceTest.cpp return failures on their assertions for the regulatory element layer
### Steps to reproduce the actual behavior

1. Open the carma_wm repository in VSCode
2. Enter the catkin_make run_tests_carma_wm command in the terminal.

**Comment by MishkaMN** [comment]
resolved by above PR
