### ISSUE TITLE
Red Truck - E-Stop Button not working

### ISSUE THREAD

**Issue by maefromm** [usdot-fhwa-stol/carma-platform#912]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

During ATEF visit last week 10/13-10/16, the e-stop button came loose and unable to put it back per Samir. 

Created ASTuff Ticket 3506 to report the issue to Ben Ross/AStuff. 

### Expected behavior
Should be working condition.

### Actual behavior

See above.

### Steps to reproduce the actual behavior
NA

### Related work

NA

**Comment by TonysCousin** [comment]
New E-stop button assembly was received by AStuff, and installed on 10/28/20 by @TonysCousin.  Testing verified correct operation.
