### ISSUE TITLE
Black Chrysler Pacifica E-Stop Button not working

### ISSUE THREAD

**Issue by lewisid** [usdot-fhwa-stol/carma-platform#913]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

While performing integration testing on the Pacifica, I pressed the e-stop and monitored the terminal for fail alerts and the UI for error messages. No matter how many times the button was pressed, there were no changes in the system status nor were there any alerts displayed on the UI. Additionally the /hardware_interface/driver_discovery topic showed no indication that the SSC had failed after pressing the button. 

It was only once CAV Guidance was set to ENGAGED that the SSC failure shutdown activated after the button was pressed. At that point, both the UI and the terminal displayed the error message indicating that the SSC had failed. 

### Expected behavior
When  the e-stop button has been pressed, the system should immediately send a failure message to the /system_alert topic, broadcast an alert to the UI and cease further operations in Carma.
### Actual behavior

The actual behavior is as described in the previous summary.
### Steps to reproduce the actual behavior

1. Run carma start all.
2. Open the UI in a browser window (Google Chrome is preferred).
3. Select an available route once prompted.
4. Open another terminal and run carma exec.
5. Monitor the /system_alert topic to see if all available drivers are functional.
6. Press the e-stop button.

**Comment by msmcconnell** [comment]
I believe this was resolved under https://github.com/usdot-fhwa-stol/carma-platform/issues/1084
Closing until evidence suggests otherwise
