### ISSUE TITLE
CARMAWebUi - Fix the Widget View and Side Bars Issues 

### ISSUE THREAD

**Issue by maefromm** [usdot-fhwa-stol/carma-platform#916]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

For the ACE Demo, 
1) Fix at a minimum the widget view to showcase the crusing plugin widget with the speedometer that's currently missing due to CARMA Guidance using Autoware Plugin. 

2) Remove the obsolete sidebar icons that are no longer needed for the ACE Demo such as the lat and lon plugin indicator, the ACC indicator, and others. 

### Carma version where this issue was discovered

Develop Branch after 3.3.0

### Expected behavior
Should display Widget View with the speedometer and other items that were under CARMA2 Cruising plugin has displayed before that are still applicable. 

### Actual behavior

Nothing is shown on Widget View and some of the side bar icons are obsolete and not populated. 

### Steps to reproduce the actual behavior

Run CARMA UI
Engage CARMA
Review the Side Bars to ensure it's working order
Review the Widget View to ensure it's working order. 

### Related work

For ACE Demo

**Comment by TonysCousin** [comment]
Missing widget view drives this to be sev 3.  Extraneous sidebar icons are sev 4 things.

**Comment by dan-du-car** [comment]
Could you specify which status icons exactly are not needed?

**Comment by msmcconnell** [comment]
Resolved by above PRs
