### ISSUE TITLE
Health_monitor node should publish SystemAlert::SHUTDOWN message upon detection of critical errors

### ISSUE THREAD

**Issue by lewisid** [usdot-fhwa-stol/carma-platform#922]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [x] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

In order to handle critical errors in the system, previously existing logic needed to be revised to display the status of the health monitor and driver nodes.

The health monitor was originally set up to publish system alert messages of type FATAL when there was a failure in both lidar and gps at the same time as well as failure in the SSC. These critical errors should cause the system to shut down immediately once they are detected, so functionality needs to be added in order to ensure that CARMA immediately shuts down in any of the aforementioned scenarios.

### Carma version where this issue was discovered

3.3.0
### Actual behavior

Please see the previous summary.

**Comment by msmcconnell** [comment]
Resolved by above PR
