### ISSUE TITLE
Small typo in carma-messenger readme

### ISSUE THREAD

**Issue by msmcconnell** [usdot-fhwa-stol/carma-platform#935]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [x] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

The carma messenger readme contains a curl command to download the carma script. This command uses the ">>" notation which appended to existing files and could cause issues with reinstallation of the system. Instead the ">" should be specified to overwrite existing installations. 

### Carma version where this issue was discovered

develop 
### Expected behavior
Instructions are not error prone
### Actual behavior

See above
### Steps to reproduce the actual behavior
Run curl commands in readme twice

**Comment by MishkaMN** [comment]
Resolved by above PR
