### ISSUE TITLE
Incident Use Case: Development of CARMA Messenger Traffic Incident Node

### ISSUE THREAD

**Issue by aswath1** [usdot-fhwa-stol/carma-platform#961]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [ x] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary
Traffic Incident node is a standalone ROS node in the CARMA Messenger. It collects data from Pinpoint driver node (e.g., latitude, longitude, heading). The traffic incident node will take the GPS data (Latitude, Longitude, Heading (Optional)),vehicle ID, up track and down track distance (It will be blocking the nearest lane for the indicated uptrack and downtrack distance from the Tahoe's position ) and publish as MobilityOperation message to the outgoingMobilityOperation topic. This will make the CARMA messenger to broadcast the Mobility Message. Please read detailed design CARMA Messenger Traffic Incident Node for more information.

### Steps to reproduce the actual behavior

1. Do this
1. Then do this...

**Comment by MishkaMN** [comment]
Resolved by above PR
