### ISSUE TITLE
If the human-readable print is uncommented, the code could crash

### ISSUE THREAD

**Issue by derrell** [usdot-fhwa-stol/carma-platform#971]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

In file [carma-messenger-core/cpp_message/src/BSM_Message.cpp](https://github.com/usdot-fhwa-stol/carma-messenger/pull/56/files#diff-5e0c5cb898321d82286d770329f4da4319efb4724d6edbe4eb3199c7d4149dd0) there is a commented-out debug statement which follows freeing of the data to be printed. Specifically, if `message` is freed before being used, depending on the local implementation of `free`, the pointers within it might be zeroed or be otherwise made invalid, and `asn_fprint` would then crash trying to dereference those pointers.

### Carma version where this issue was discovered

carma-messenger `develop` as of 3 Nov 2020

### Steps to reproduce the actual behavior

1. Do this
1. Then do this...

**Comment by msmcconnell** [comment]
Resolved by above PR
