### ISSUE TITLE
One byte of formatted data could be lost

### ISSUE THREAD

**Issue by derrell** [usdot-fhwa-stol/carma-platform#972]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

This is ascertained solely by inspection. I am not yet able to build and test the system. That said...

Reference the files in carma-messenger-core/cpp_message/src/ and for the purpose of description, the specific file BSM_Message.cpp:

My understanding is that `uper_encode_to_buffer` provides, in the `encoded` member of the returned structure, the number of bits of packed data that were formatted. Unless there is a guarantee that the number of bits will always be a multiple of 8, there appears to be a possibility of losing the last byte.

### Carma version where this issue was discovered

carma-messenger `develop` as of 3 Nov 2020

### Expected behavior
All bytes of the formatted data are returned to the caller.

### Actual behavior

It appears that there is a possibility that the final byte of the formatted data is not copied to the buffer returned to the caller.

### Steps to reproduce the actual behavior

1. Do this
1. Then do this...

**Comment by msmcconnell** [comment]
Resolved by above PR
