### ISSUE TITLE
License plate number shown in truck inspection log is wrong

### ISSUE THREAD

**Issue by snallamothu** [usdot-fhwa-stol/carma-platform#973]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary
Truck inspection log received from the White truck shows license plate number as DOT-10003 instead of DOT-10004. 

### Carma version where this issue was discovered
Wanderer

### Expected behavior
License plate number broadcast by CARMA platform for this truck should have been DOT-10004.

### Actual behavior
See issue description

### Steps to reproduce the actual behavior
1. Run the truck CARMA engaged
2.  Verify that CARMA messenger detects the vehicle
3. Request log and inspect the inspection log received

### Related work
![Screenshot from 2020-11-12 15-53-55](https://user-images.githubusercontent.com/3028188/99396288-9048a580-28af-11eb-975f-a818d3a38c9e.png)

**Comment by dan-du-car** [comment]
Per ACE testing, verified that CARMA platform running in different trucks' PCs can publish different license plate numbers. The Taheo nearby can receive the truck logs and display the license plate numbers fine.  So this is no longer an issue.
