### ISSUE TITLE
carma_wm_ctrl overwrites map speed limit

### ISSUE THREAD

**Issue by adev4a** [usdot-fhwa-stol/carma-platform#974]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

When querying route speed limit for CAR-3825 https://usdot-carma.atlassian.net/browse/CAR-3825, speed limit returned is the config_speed_limit, as seen in the UI.

### Carma version where this issue was discovered

Integration/routing

### Expected behavior
Speed limit displayed in UI should be the speed limit in the vector map.
### Actual behavior
Speed limit displayed in the UI is the vehicle config speed limit, from carma-config.

### Steps to reproduce the actual behavior

Test on vehicle
1. Edit the vector map linked to vector_map.osm in /opt/carma/routes to have a fixed speed limit of 20mph for all digitalspeedlimit regulation elements.
2. Start CARMA and launch the UI while on the route.

**Comment by msmcconnell** [comment]
Resolved by above PR
