### ISSUE TITLE
Adaptive lookahead distance for in-lane cruising

### ISSUE THREAD

**Issue by saina-ramyar** [usdot-fhwa-stol/carma-platform#988]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [x] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary
Currently, the in-lane cruising has a constant lookahead distance for adjusting the speed of trajectory. However, depending on the vehicle's speed, the lookahead needs to be different. If the vehicle's velocity is high and it is approaching a low-speed area such as a tight curve, it must be aware well in advance.
Therefore, the lookahead distance should be adaptive with speed, so it can be large when the vehicle is moving fast, and small if the vehicle is moving slowly.

### Expected behavior'
Lookahead distance should be changed based n the vehicle's velocity.

### Actual behavior

The lookahead distance is a constant number of points ahead.

### Steps to reproduce the actual behavior

1. Do this
1. Then do this...

**Comment by msmcconnell** [comment]
Resolved by above PR
