### ISSUE TITLE
Display route on rviz

### ISSUE THREAD

**Issue by aswath1** [usdot-fhwa-stol/carma-platform#991]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [x] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary
Now that we are no longer using waypoints in the planning process, the route cannot be visualized on rviz via waypoints. An alternate visualization method should be employed. This story is to design and implement a simple way to visualize the loaded route in rviz without blocking the view of the vehicle or lanelets when in top down view on rviz. The easiest method would be to add a publisher to the route node which publishes rviz markers. Effort should be made to separate this logic from the core route planning logic so that could stays easy to read.

### Steps to reproduce the actual behavior

1. Do this
1. Then do this...

**Comment by MishkaMN** [comment]
Resolved w above PR
